-- Comprehensive Cancer Mutation Database
-- Based on COSMIC Cancer Gene Census, OncoKB, and FDA approvals 2024
-- This script populates the database with hundreds of genes and therapeutic options

-- Clear existing data
DELETE FROM study_therapeutics;
DELETE FROM clinical_studies;
DELETE FROM mutation_hotspots;
DELETE FROM therapeutic_cancer_types;
DELETE FROM therapeutics;
DELETE FROM mutations;
DELETE FROM cancer_types;
DELETE FROM genes;
DELETE FROM sqlite_sequence;

-- ==========================================
-- CANCER TYPES (Expanded list)
-- ==========================================
INSERT INTO cancer_types (cancer_name, tissue_origin, description) VALUES
-- Common cancers
('Non-Small Cell Lung Cancer', 'Lung', 'Most common type of lung cancer, includes adenocarcinoma and squamous cell'),
('Small Cell Lung Cancer', 'Lung', 'Aggressive form of lung cancer'),
('Triple-Negative Breast Cancer', 'Breast', 'Aggressive breast cancer lacking ER, PR, and HER2'),
('HR+ Breast Cancer', 'Breast', 'Hormone receptor positive breast cancer'),
('HER2+ Breast Cancer', 'Breast', 'HER2 amplified breast cancer'),
('Colorectal Adenocarcinoma', 'Colon', 'Most common type of colorectal cancer'),
('Cutaneous Melanoma', 'Skin', 'Most common type of melanoma'),
('Uveal Melanoma', 'Eye', 'Rare melanoma of the eye'),
('Pancreatic Adenocarcinoma', 'Pancreas', 'Most common and aggressive pancreatic cancer'),
('Hepatocellular Carcinoma', 'Liver', 'Primary liver cancer'),
('Clear Cell Ovarian Cancer', 'Ovary', 'Subtype of epithelial ovarian cancer'),
('Serous Ovarian Cancer', 'Ovary', 'Most common ovarian cancer subtype'),
('Glioblastoma Multiforme', 'Brain', 'Most aggressive brain tumor'),
('Low-Grade Glioma', 'Brain', 'Slower growing brain tumors'),
('Papillary Thyroid Cancer', 'Thyroid', 'Most common thyroid cancer'),
('Follicular Thyroid Cancer', 'Thyroid', 'Second most common thyroid cancer'),
('Anaplastic Thyroid Cancer', 'Thyroid', 'Rare aggressive thyroid cancer'),
('Clear Cell Renal Cell Carcinoma', 'Kidney', 'Most common kidney cancer'),
('Papillary Renal Cell Carcinoma', 'Kidney', 'Second most common kidney cancer'),
('Urothelial Carcinoma', 'Bladder', 'Most common bladder cancer'),
('Adenocarcinoma of Prostate', 'Prostate', 'Most common prostate cancer'),
('Castration-Resistant Prostate Cancer', 'Prostate', 'Advanced prostate cancer'),
('Gastric Adenocarcinoma', 'Stomach', 'Most common stomach cancer'),
('Esophageal Adenocarcinoma', 'Esophagus', 'Common in Western countries'),
('Esophageal Squamous Cell Carcinoma', 'Esophagus', 'Common in Asia'),
('Head and Neck Squamous Cell Carcinoma', 'Head/Neck', 'Includes oral, pharyngeal cancers'),
('Nasopharyngeal Carcinoma', 'Head/Neck', 'EBV-associated cancer'),
('Acute Myeloid Leukemia', 'Blood', 'Most common adult leukemia'),
('Acute Lymphoblastic Leukemia', 'Blood', 'Most common childhood leukemia'),
('Chronic Myeloid Leukemia', 'Blood', 'BCR-ABL driven leukemia'),
('Chronic Lymphocytic Leukemia', 'Blood', 'Most common adult leukemia in West'),
('Diffuse Large B-Cell Lymphoma', 'Lymphoid', 'Most common lymphoma'),
('Follicular Lymphoma', 'Lymphoid', 'Second most common lymphoma'),
('Mantle Cell Lymphoma', 'Lymphoid', 'Aggressive B-cell lymphoma'),
('Hodgkin Lymphoma', 'Lymphoid', 'Reed-Sternberg cell lymphoma'),
('Multiple Myeloma', 'Bone Marrow', 'Plasma cell malignancy'),
('Myelodysplastic Syndrome', 'Bone Marrow', 'Preleukemic condition'),
('Myeloproliferative Neoplasms', 'Bone Marrow', 'Includes PV, ET, MF'),
('Gastrointestinal Stromal Tumor', 'GI Tract', 'KIT/PDGFRA driven sarcoma'),
('Leiomyosarcoma', 'Soft Tissue', 'Smooth muscle sarcoma'),
('Liposarcoma', 'Soft Tissue', 'Adipose tissue sarcoma'),
('Synovial Sarcoma', 'Soft Tissue', 'Rare soft tissue sarcoma'),
('Ewing Sarcoma', 'Bone', 'Pediatric bone cancer'),
('Osteosarcoma', 'Bone', 'Primary bone cancer'),
('Chondrosarcoma', 'Bone', 'Cartilage cancer'),
('Mesothelioma', 'Pleura', 'Asbestos-related cancer'),
('Cholangiocarcinoma', 'Bile Duct', 'Bile duct cancer'),
('Gallbladder Cancer', 'Gallbladder', 'Rare aggressive cancer'),
('Neuroendocrine Tumors', 'Various', 'Hormone-producing tumors'),
('Carcinoid Tumors', 'Various', 'Slow-growing neuroendocrine tumors'),
('Pheochromocytoma', 'Adrenal', 'Catecholamine-producing tumor'),
('Adrenocortical Carcinoma', 'Adrenal', 'Rare aggressive adrenal cancer'),
('Testicular Cancer', 'Testis', 'Germ cell tumors'),
('Endometrial Cancer', 'Uterus', 'Most common gynecologic cancer'),
('Cervical Cancer', 'Cervix', 'HPV-associated cancer'),
('Vulvar Cancer', 'Vulva', 'Rare gynecologic cancer'),
('Vaginal Cancer', 'Vagina', 'Very rare gynecologic cancer'),
('Penile Cancer', 'Penis', 'Rare cancer in men'),
('Merkel Cell Carcinoma', 'Skin', 'Aggressive neuroendocrine skin cancer'),
('Basal Cell Carcinoma', 'Skin', 'Most common skin cancer'),
('Squamous Cell Carcinoma of Skin', 'Skin', 'Second most common skin cancer'),
('Kaposi Sarcoma', 'Skin/Mucosa', 'HHV8-associated cancer'),
('Angiosarcoma', 'Blood Vessels', 'Rare vascular cancer'),
('Neuroblastoma', 'Neural', 'Pediatric neural crest tumor'),
('Medulloblastoma', 'Brain', 'Pediatric brain tumor'),
('Retinoblastoma', 'Eye', 'Pediatric eye cancer'),
('Wilms Tumor', 'Kidney', 'Pediatric kidney cancer'),
('Rhabdomyosarcoma', 'Muscle', 'Pediatric muscle cancer'),
('Hepatoblastoma', 'Liver', 'Pediatric liver cancer');

-- ==========================================
-- GENES (719 from COSMIC Cancer Gene Census + OncoKB)
-- ==========================================
INSERT INTO genes (gene_symbol, gene_name, chromosome, gene_type, description) VALUES
-- Major Oncogenes (Tier 1)
('ABL1', 'ABL proto-oncogene 1', '9q34.12', 'oncogene', 'Tyrosine kinase, BCR-ABL fusion in CML'),
('AKT1', 'AKT serine/threonine kinase 1', '14q32.33', 'oncogene', 'PI3K/AKT pathway activator'),
('AKT2', 'AKT serine/threonine kinase 2', '19q13.2', 'oncogene', 'PI3K/AKT pathway member'),
('AKT3', 'AKT serine/threonine kinase 3', '1q43-q44', 'oncogene', 'PI3K/AKT pathway member'),
('ALK', 'Anaplastic lymphoma kinase', '2p23.1', 'oncogene', 'Receptor tyrosine kinase, fusion driver'),
('APC', 'Adenomatous polyposis coli', '5q22.2', 'tumor_suppressor', 'WNT pathway regulator'),
('AR', 'Androgen receptor', 'Xq12', 'oncogene', 'Nuclear receptor, prostate cancer driver'),
('ARAF', 'A-Raf proto-oncogene', 'Xp11.3', 'oncogene', 'RAF kinase family member'),
('ARID1A', 'AT-rich interaction domain 1A', '1p36.11', 'tumor_suppressor', 'SWI/SNF chromatin remodeling'),
('ARID1B', 'AT-rich interaction domain 1B', '6q25.3', 'tumor_suppressor', 'SWI/SNF chromatin remodeling'),
('ARID2', 'AT-rich interaction domain 2', '12q12', 'tumor_suppressor', 'SWI/SNF chromatin remodeling'),
('ASXL1', 'ASXL transcriptional regulator 1', '20q11.21', 'tumor_suppressor', 'Chromatin modifier'),
('ASXL2', 'ASXL transcriptional regulator 2', '2p23.3', 'tumor_suppressor', 'Chromatin modifier'),
('ATM', 'Ataxia telangiectasia mutated', '11q22.3', 'tumor_suppressor', 'DNA damage checkpoint'),
('ATR', 'ATR serine/threonine kinase', '3q23', 'tumor_suppressor', 'DNA damage response'),
('ATRX', 'ATRX chromatin remodeler', 'Xq21.1', 'tumor_suppressor', 'Chromatin remodeling, telomere maintenance'),
('AURKA', 'Aurora kinase A', '20q13.2', 'oncogene', 'Mitotic kinase'),
('AURKB', 'Aurora kinase B', '17p13.1', 'oncogene', 'Mitotic kinase'),
('AXIN1', 'Axin 1', '16p13.3', 'tumor_suppressor', 'WNT pathway regulator'),
('AXIN2', 'Axin 2', '17q24.1', 'tumor_suppressor', 'WNT pathway regulator'),
('AXL', 'AXL receptor tyrosine kinase', '19q13.2', 'oncogene', 'TAM receptor family'),

-- B genes
('B2M', 'Beta-2-microglobulin', '15q21.1', 'tumor_suppressor', 'MHC class I component'),
('BAP1', 'BRCA1 associated protein 1', '3p21.1', 'tumor_suppressor', 'Deubiquitinase, DNA repair'),
('BARD1', 'BRCA1 associated RING domain 1', '2q35', 'tumor_suppressor', 'BRCA1 partner in DNA repair'),
('BCL2', 'BCL2 apoptosis regulator', '18q21.33', 'oncogene', 'Anti-apoptotic protein'),
('BCL2L1', 'BCL2 like 1', '20q11.21', 'oncogene', 'Anti-apoptotic BCL-XL'),
('BCL2L11', 'BCL2 like 11', '2q13', 'tumor_suppressor', 'Pro-apoptotic BIM'),
('BCL6', 'BCL6 transcription repressor', '3q27.3', 'oncogene', 'Germinal center master regulator'),
('BCOR', 'BCL6 corepressor', 'Xp11.4', 'tumor_suppressor', 'Transcriptional corepressor'),
('BCORL1', 'BCL6 corepressor like 1', 'Xq26.1', 'tumor_suppressor', 'Transcriptional corepressor'),
('BCR', 'BCR activator of RhoGEF', '22q11.23', 'oncogene', 'BCR-ABL fusion partner'),
('BIRC3', 'Baculoviral IAP repeat containing 3', '11q22.2', 'tumor_suppressor', 'Apoptosis inhibitor'),
('BLM', 'Bloom syndrome RecQ like helicase', '15q26.1', 'tumor_suppressor', 'DNA helicase, genome stability'),
('BMPR1A', 'Bone morphogenetic protein receptor 1A', '10q23.2', 'tumor_suppressor', 'TGF-β/BMP signaling'),
('BRAF', 'B-Raf proto-oncogene', '7q34', 'oncogene', 'Serine/threonine kinase in MAPK pathway'),
('BRCA1', 'Breast cancer type 1', '17q21.31', 'tumor_suppressor', 'DNA damage repair, homologous recombination'),
('BRCA2', 'Breast cancer type 2', '13q13.1', 'tumor_suppressor', 'DNA damage repair, homologous recombination'),
('BRD4', 'Bromodomain containing 4', '19p13.12', 'oncogene', 'Chromatin reader, super-enhancers'),
('BRIP1', 'BRCA1 interacting helicase 1', '17q23.2', 'tumor_suppressor', 'DNA repair helicase'),
('BTG1', 'BTG anti-proliferation factor 1', '12q21.33', 'tumor_suppressor', 'Cell cycle regulation'),
('BTK', 'Bruton tyrosine kinase', 'Xq22.1', 'oncogene', 'B-cell receptor signaling'),

-- C genes
('CALR', 'Calreticulin', '19p13.2', 'oncogene', 'ER chaperone, mutated in MPN'),
('CARD11', 'CARD domain containing 11', '7p22.2', 'oncogene', 'NF-κB signaling'),
('CARM1', 'Coactivator associated arginine methyltransferase 1', '19p13.2', 'oncogene', 'Histone methyltransferase'),
('CASP8', 'Caspase 8', '2q33.1', 'tumor_suppressor', 'Apoptosis initiator'),
('CBFB', 'Core-binding factor subunit beta', '16q22.1', 'oncogene', 'Transcription factor, fusion in AML'),
('CBL', 'Cbl proto-oncogene', '11q23.3', 'tumor_suppressor', 'E3 ubiquitin ligase'),
('CCND1', 'Cyclin D1', '11q13.3', 'oncogene', 'Cell cycle G1/S transition'),
('CCND2', 'Cyclin D2', '12p13.32', 'oncogene', 'Cell cycle regulation'),
('CCND3', 'Cyclin D3', '6p21.1', 'oncogene', 'Cell cycle regulation'),
('CCNE1', 'Cyclin E1', '19q12', 'oncogene', 'Cell cycle G1/S transition'),
('CD274', 'CD274 molecule (PD-L1)', '9p24.1', 'oncogene', 'Immune checkpoint ligand'),
('CD276', 'CD276 molecule (B7-H3)', '15q24.1', 'oncogene', 'Immune checkpoint molecule'),
('CD79A', 'CD79a molecule', '19q13.2', 'oncogene', 'B-cell receptor signaling'),
('CD79B', 'CD79b molecule', '17q23.3', 'oncogene', 'B-cell receptor signaling'),
('CDC73', 'Cell division cycle 73', '1q31.2', 'tumor_suppressor', 'Parafibromin, transcriptional regulation'),
('CDH1', 'Cadherin 1 (E-cadherin)', '16q22.1', 'tumor_suppressor', 'Cell adhesion, EMT suppressor'),
('CDK12', 'Cyclin dependent kinase 12', '17q12', 'tumor_suppressor', 'Transcription, DNA repair'),
('CDK4', 'Cyclin dependent kinase 4', '12q14.1', 'oncogene', 'Cell cycle regulator'),
('CDK6', 'Cyclin dependent kinase 6', '7q21.2', 'oncogene', 'Cell cycle regulator'),
('CDK8', 'Cyclin dependent kinase 8', '13q12.13', 'oncogene', 'Transcriptional regulation'),
('CDKN1A', 'Cyclin dependent kinase inhibitor 1A (p21)', '6p21.2', 'tumor_suppressor', 'Cell cycle inhibitor'),
('CDKN1B', 'Cyclin dependent kinase inhibitor 1B (p27)', '12p13.1', 'tumor_suppressor', 'Cell cycle inhibitor'),
('CDKN2A', 'Cyclin dependent kinase inhibitor 2A', '9p21.3', 'tumor_suppressor', 'p16/p14ARF, cell cycle inhibitor'),
('CDKN2B', 'Cyclin dependent kinase inhibitor 2B', '9p21.3', 'tumor_suppressor', 'p15, cell cycle inhibitor'),
('CDKN2C', 'Cyclin dependent kinase inhibitor 2C', '1p32.3', 'tumor_suppressor', 'p18, cell cycle inhibitor'),
('CEBPA', 'CCAAT enhancer binding protein alpha', '19q13.11', 'tumor_suppressor', 'Myeloid differentiation'),
('CENPA', 'Centromere protein A', '2p23.3', 'oncogene', 'Centromere function'),
('CHEK1', 'Checkpoint kinase 1', '11q24.2', 'tumor_suppressor', 'DNA damage checkpoint'),
('CHEK2', 'Checkpoint kinase 2', '22q12.1', 'tumor_suppressor', 'DNA damage checkpoint'),
('CIC', 'Capicua transcriptional repressor', '19q13.2', 'tumor_suppressor', 'Transcriptional repressor'),
('CREBBP', 'CREB binding protein', '16p13.3', 'tumor_suppressor', 'Histone acetyltransferase'),
('CRKL', 'CRK like proto-oncogene', '22q11.21', 'oncogene', 'Adaptor protein'),
('CRLF2', 'Cytokine receptor like factor 2', 'Xp22.33', 'oncogene', 'Cytokine receptor'),
('CSF1R', 'Colony stimulating factor 1 receptor', '5q32', 'oncogene', 'Receptor tyrosine kinase'),
('CSF3R', 'Colony stimulating factor 3 receptor', '1p34.3', 'oncogene', 'Cytokine receptor'),
('CTCF', 'CCCTC-binding factor', '16q22.1', 'tumor_suppressor', 'Chromatin organization'),
('CTLA4', 'Cytotoxic T-lymphocyte associated protein 4', '2q33.2', 'tumor_suppressor', 'Immune checkpoint'),
('CTNNB1', 'Catenin beta 1', '3p22.1', 'oncogene', 'Beta-catenin, WNT pathway'),
('CUL3', 'Cullin 3', '2q36.2', 'tumor_suppressor', 'E3 ubiquitin ligase'),
('CUX1', 'Cut like homeobox 1', '7q22.1', 'tumor_suppressor', 'Transcription factor'),
('CXCR4', 'C-X-C motif chemokine receptor 4', '2q22.1', 'oncogene', 'Chemokine receptor'),
('CYLD', 'CYLD lysine 63 deubiquitinase', '16q12.1', 'tumor_suppressor', 'Deubiquitinase, NF-κB regulation'),
('CYP2D6', 'Cytochrome P450 2D6', '22q13.2', 'other', 'Drug metabolism'),

-- D genes
('DAXX', 'Death domain associated protein', '6p21.32', 'tumor_suppressor', 'Chromatin remodeling, apoptosis'),
('DDB2', 'Damage specific DNA binding protein 2', '11p11.2', 'tumor_suppressor', 'DNA repair'),
('DDR2', 'Discoidin domain receptor 2', '1q23.3', 'oncogene', 'Receptor tyrosine kinase'),
('DDX3X', 'DEAD-box helicase 3 X-linked', 'Xp11.4', 'tumor_suppressor', 'RNA helicase'),
('DDX41', 'DEAD-box helicase 41', '5q35.3', 'tumor_suppressor', 'RNA/DNA helicase'),
('DEK', 'DEK proto-oncogene', '6p22.3', 'oncogene', 'Chromatin organization'),
('DICER1', 'Dicer 1, ribonuclease III', '14q32.13', 'tumor_suppressor', 'miRNA processing'),
('DIS3', 'DIS3 homolog, exosome endoribonuclease', '13q22.1', 'tumor_suppressor', 'RNA exosome'),
('DNAJB1', 'DnaJ heat shock protein family member B1', '19p13.12', 'oncogene', 'Heat shock protein'),
('DNMT1', 'DNA methyltransferase 1', '19p13.2', 'oncogene', 'DNA methylation maintenance'),
('DNMT3A', 'DNA methyltransferase 3 alpha', '2p23.3', 'tumor_suppressor', 'De novo DNA methylation'),
('DNMT3B', 'DNA methyltransferase 3 beta', '20q11.21', 'oncogene', 'De novo DNA methylation'),
('DOT1L', 'DOT1 like histone lysine methyltransferase', '19p13.3', 'oncogene', 'Histone H3K79 methyltransferase'),
('DROSHA', 'Drosha ribonuclease III', '5p13.3', 'tumor_suppressor', 'miRNA processing'),
('DUSP4', 'Dual specificity phosphatase 4', '8p12', 'tumor_suppressor', 'MAPK pathway regulation'),

-- E genes
('E2F3', 'E2F transcription factor 3', '6p22.3', 'oncogene', 'Cell cycle transcription factor'),
('EED', 'Embryonic ectoderm development', '11q14.2', 'tumor_suppressor', 'PRC2 complex'),
('EGFL7', 'EGF like domain multiple 7', '9q34.3', 'oncogene', 'Angiogenesis'),
('EGFR', 'Epidermal growth factor receptor', '7p11.2', 'oncogene', 'Receptor tyrosine kinase'),
('EIF1AX', 'Eukaryotic translation initiation factor 1A X-linked', 'Xp22.12', 'oncogene', 'Translation initiation'),
('EIF4A2', 'Eukaryotic translation initiation factor 4A2', '3q27.3', 'oncogene', 'Translation initiation'),
('EIF4E', 'Eukaryotic translation initiation factor 4E', '4q23', 'oncogene', 'Translation initiation'),
('ELF3', 'E74 like ETS transcription factor 3', '1q32.1', 'tumor_suppressor', 'ETS family transcription factor'),
('EML4', 'EMAP like 4', '2p21', 'oncogene', 'EML4-ALK fusion partner'),
('EP300', 'E1A binding protein p300', '22q13.2', 'tumor_suppressor', 'Histone acetyltransferase'),
('EPAS1', 'Endothelial PAS domain protein 1 (HIF2A)', '2p21', 'oncogene', 'Hypoxia response'),
('EPCAM', 'Epithelial cell adhesion molecule', '2p21', 'oncogene', 'Cell adhesion'),
('EPHA2', 'EPH receptor A2', '1p36.13', 'oncogene', 'Receptor tyrosine kinase'),
('EPHA3', 'EPH receptor A3', '3p11.1', 'tumor_suppressor', 'Receptor tyrosine kinase'),
('EPHA5', 'EPH receptor A5', '4q13.1', 'tumor_suppressor', 'Receptor tyrosine kinase'),
('EPHA7', 'EPH receptor A7', '6q16.1', 'tumor_suppressor', 'Receptor tyrosine kinase'),
('EPHB1', 'EPH receptor B1', '3q22.2', 'tumor_suppressor', 'Receptor tyrosine kinase'),
('ERBB2', 'Erb-b2 receptor tyrosine kinase 2 (HER2)', '17q12', 'oncogene', 'Receptor tyrosine kinase'),
('ERBB3', 'Erb-b2 receptor tyrosine kinase 3', '12q13.2', 'oncogene', 'HER3, EGF receptor family'),
('ERBB4', 'Erb-b2 receptor tyrosine kinase 4', '2q34', 'oncogene', 'HER4, EGF receptor family'),
('ERCC2', 'ERCC excision repair 2', '19q13.32', 'tumor_suppressor', 'DNA repair'),
('ERCC3', 'ERCC excision repair 3', '2q14.3', 'tumor_suppressor', 'DNA repair'),
('ERCC4', 'ERCC excision repair 4', '16p13.12', 'tumor_suppressor', 'DNA repair'),
('ERCC5', 'ERCC excision repair 5', '13q33.1', 'tumor_suppressor', 'DNA repair'),
('ERG', 'ETS transcription factor ERG', '21q22.2', 'oncogene', 'ETS family, TMPRSS2-ERG fusion'),
('ERRFI1', 'ERBB receptor feedback inhibitor 1', '1p36.21', 'tumor_suppressor', 'EGFR inhibitor'),
('ESR1', 'Estrogen receptor 1', '6q25.1', 'oncogene', 'Nuclear hormone receptor'),
('ETS1', 'ETS proto-oncogene 1', '11q24.3', 'oncogene', 'ETS transcription factor'),
('ETV1', 'ETS variant transcription factor 1', '7p21.2', 'oncogene', 'ETS family'),
('ETV4', 'ETS variant transcription factor 4', '17q21.31', 'oncogene', 'ETS family'),
('ETV5', 'ETS variant transcription factor 5', '3q27.2', 'oncogene', 'ETS family'),
('ETV6', 'ETS variant transcription factor 6', '12p13.2', 'tumor_suppressor', 'ETS family, fusion partner'),
('EWSR1', 'EWS RNA binding protein 1', '22q12.2', 'oncogene', 'Ewing sarcoma fusion'),
('EXT1', 'Exostosin glycosyltransferase 1', '8q24.11', 'tumor_suppressor', 'Heparan sulfate synthesis'),
('EXT2', 'Exostosin glycosyltransferase 2', '11p11.2', 'tumor_suppressor', 'Heparan sulfate synthesis'),
('EZH2', 'Enhancer of zeste 2', '7q36.1', 'oncogene', 'PRC2 complex, H3K27 methyltransferase'),

-- F genes
('FAM175A', 'Family with sequence similarity 175 member A', '4q21.23', 'tumor_suppressor', 'DNA repair'),
('FAM46C', 'Family with sequence similarity 46 member C', '1p12', 'tumor_suppressor', 'mRNA stability'),
('FAM58A', 'Family with sequence similarity 58 member A', 'Xq28', 'tumor_suppressor', 'Unknown function'),
('FANCA', 'FA complementation group A', '16q24.3', 'tumor_suppressor', 'DNA repair, Fanconi anemia'),
('FANCC', 'FA complementation group C', '9q22.32', 'tumor_suppressor', 'DNA repair, Fanconi anemia'),
('FANCD2', 'FA complementation group D2', '3p25.3', 'tumor_suppressor', 'DNA repair, Fanconi anemia'),
('FANCE', 'FA complementation group E', '6p21.31', 'tumor_suppressor', 'DNA repair, Fanconi anemia'),
('FANCF', 'FA complementation group F', '11p14.3', 'tumor_suppressor', 'DNA repair, Fanconi anemia'),
('FANCG', 'FA complementation group G', '9p13.3', 'tumor_suppressor', 'DNA repair, Fanconi anemia'),
('FANCL', 'FA complementation group L', '2p16.1', 'tumor_suppressor', 'DNA repair, Fanconi anemia'),
('FAS', 'Fas cell surface death receptor', '10q23.31', 'tumor_suppressor', 'Apoptosis receptor'),
('FAT1', 'FAT atypical cadherin 1', '4q35.2', 'tumor_suppressor', 'Cell adhesion, Hippo pathway'),
('FAT3', 'FAT atypical cadherin 3', '11q14.3', 'tumor_suppressor', 'Cell adhesion'),
('FAT4', 'FAT atypical cadherin 4', '4q28.1', 'tumor_suppressor', 'Cell adhesion, Hippo pathway'),
('FBXO11', 'F-box protein 11', '2p16.3', 'tumor_suppressor', 'Protein degradation'),
('FBXW7', 'F-box and WD repeat domain containing 7', '4q31.3', 'tumor_suppressor', 'SCF complex, protein degradation'),
('FGF19', 'Fibroblast growth factor 19', '11q13.3', 'oncogene', 'Growth factor'),
('FGF3', 'Fibroblast growth factor 3', '11q13.3', 'oncogene', 'Growth factor'),
('FGF4', 'Fibroblast growth factor 4', '11q13.3', 'oncogene', 'Growth factor'),
('FGFR1', 'Fibroblast growth factor receptor 1', '8p11.23', 'oncogene', 'Receptor tyrosine kinase'),
('FGFR2', 'Fibroblast growth factor receptor 2', '10q26.13', 'oncogene', 'Receptor tyrosine kinase'),
('FGFR3', 'Fibroblast growth factor receptor 3', '4p16.3', 'oncogene', 'Receptor tyrosine kinase'),
('FGFR4', 'Fibroblast growth factor receptor 4', '5q35.2', 'oncogene', 'Receptor tyrosine kinase'),
('FH', 'Fumarate hydratase', '1q43', 'tumor_suppressor', 'TCA cycle enzyme'),
('FLCN', 'Folliculin', '17p11.2', 'tumor_suppressor', 'mTOR pathway regulation'),
('FLI1', 'Fli-1 proto-oncogene', '11q24.3', 'oncogene', 'ETS family transcription factor'),
('FLT1', 'Fms related receptor tyrosine kinase 1', '13q12.3', 'oncogene', 'VEGFR1, angiogenesis'),
('FLT3', 'Fms related receptor tyrosine kinase 3', '13q12.2', 'oncogene', 'Receptor tyrosine kinase'),
('FLT4', 'Fms related receptor tyrosine kinase 4', '5q35.3', 'oncogene', 'VEGFR3, lymphangiogenesis'),
('FOXA1', 'Forkhead box A1', '14q21.1', 'oncogene', 'Pioneer transcription factor'),
('FOXL2', 'Forkhead box L2', '3q22.3', 'tumor_suppressor', 'Transcription factor'),
('FOXO1', 'Forkhead box O1', '13q14.11', 'tumor_suppressor', 'Transcription factor'),
('FOXP1', 'Forkhead box P1', '3p13', 'tumor_suppressor', 'Transcription factor'),
('FUBP1', 'Far upstream element binding protein 1', '1p31.1', 'tumor_suppressor', 'RNA/DNA binding'),
('FYN', 'FYN proto-oncogene', '6q21', 'oncogene', 'Src family kinase'),

-- G genes
('GABRA6', 'Gamma-aminobutyric acid type A receptor subunit alpha6', '5q34', 'tumor_suppressor', 'GABA receptor'),
('GATA1', 'GATA binding protein 1', 'Xp11.23', 'oncogene', 'Hematopoietic transcription factor'),
('GATA2', 'GATA binding protein 2', '3q21.3', 'oncogene', 'Hematopoietic transcription factor'),
('GATA3', 'GATA binding protein 3', '10p14', 'tumor_suppressor', 'Transcription factor'),
('GID4', 'GID complex subunit 4', '17p11.2', 'tumor_suppressor', 'Protein degradation'),
('GLI1', 'GLI family zinc finger 1', '12q13.3', 'oncogene', 'Hedgehog pathway'),
('GNA11', 'G protein subunit alpha 11', '19p13.3', 'oncogene', 'G-protein signaling'),
('GNA13', 'G protein subunit alpha 13', '17q25.3', 'oncogene', 'G-protein signaling'),
('GNAQ', 'G protein subunit alpha q', '9q21.2', 'oncogene', 'G-protein signaling'),
('GNAS', 'GNAS complex locus', '20q13.32', 'oncogene', 'G-protein signaling'),
('GPS2', 'G protein pathway suppressor 2', '17p13.1', 'tumor_suppressor', 'Transcriptional corepressor'),
('GREM1', 'Gremlin 1', '15q13.3', 'oncogene', 'BMP antagonist'),
('GRIN2A', 'Glutamate ionotropic receptor NMDA type subunit 2A', '16p13.2', 'tumor_suppressor', 'NMDA receptor'),
('GRM3', 'Glutamate metabotropic receptor 3', '7q21.11', 'tumor_suppressor', 'Metabotropic glutamate receptor'),
('GSK3B', 'Glycogen synthase kinase 3 beta', '3q13.33', 'tumor_suppressor', 'WNT pathway regulation'),
('GSTP1', 'Glutathione S-transferase pi 1', '11q13.2', 'tumor_suppressor', 'Detoxification'),

-- H genes
('H3F3A', 'H3.3 histone A', '1q42.12', 'oncogene', 'Histone variant'),
('H3F3B', 'H3.3 histone B', '17q25.1', 'oncogene', 'Histone variant'),
('HGF', 'Hepatocyte growth factor', '7q21.11', 'oncogene', 'Growth factor for MET'),
('HIF1A', 'Hypoxia inducible factor 1 subunit alpha', '14q23.2', 'oncogene', 'Hypoxia response'),
('HIST1H1C', 'H1.2 linker histone', '6p22.1', 'tumor_suppressor', 'Chromatin compaction'),
('HIST1H3B', 'H3 clustered histone 3', '6p22.2', 'oncogene', 'Core histone'),
('HLA-A', 'Major histocompatibility complex, class I, A', '6p22.1', 'tumor_suppressor', 'Antigen presentation'),
('HLA-B', 'Major histocompatibility complex, class I, B', '6p21.33', 'tumor_suppressor', 'Antigen presentation'),
('HLA-C', 'Major histocompatibility complex, class I, C', '6p21.33', 'tumor_suppressor', 'Antigen presentation'),
('HNF1A', 'HNF1 homeobox A', '12q24.31', 'tumor_suppressor', 'Transcription factor'),
('HNRNPA2B1', 'Heterogeneous nuclear ribonucleoprotein A2/B1', '7p15.2', 'oncogene', 'RNA processing'),
('HOXB13', 'Homeobox B13', '17q21.32', 'oncogene', 'Transcription factor'),
('HRAS', 'HRas proto-oncogene', '11p15.5', 'oncogene', 'RAS family GTPase'),
('HSP90AA1', 'Heat shock protein 90 alpha family class A member 1', '14q32.31', 'oncogene', 'Molecular chaperone'),
('HSP90AB1', 'Heat shock protein 90 alpha family class B member 1', '6p21.1', 'oncogene', 'Molecular chaperone'),

-- I genes
('ID3', 'Inhibitor of DNA binding 3', '1p36.12', 'tumor_suppressor', 'Transcriptional regulator'),
('IDH1', 'Isocitrate dehydrogenase (NADP(+)) 1', '2q34', 'oncogene', 'Metabolic enzyme, neomorphic'),
('IDH2', 'Isocitrate dehydrogenase (NADP(+)) 2', '15q26.1', 'oncogene', 'Metabolic enzyme, neomorphic'),
('IFNGR1', 'Interferon gamma receptor 1', '6q23.3', 'tumor_suppressor', 'Cytokine receptor'),
('IGF1', 'Insulin like growth factor 1', '12q23.2', 'oncogene', 'Growth factor'),
('IGF1R', 'Insulin like growth factor 1 receptor', '15q26.3', 'oncogene', 'Receptor tyrosine kinase'),
('IGF2', 'Insulin like growth factor 2', '11p15.5', 'oncogene', 'Growth factor'),
('IKBKE', 'Inhibitor of nuclear factor kappa B kinase subunit epsilon', '1q32.1', 'oncogene', 'NF-κB activation'),
('IKZF1', 'IKAROS family zinc finger 1', '7p12.2', 'tumor_suppressor', 'Lymphoid transcription factor'),
('IL2', 'Interleukin 2', '4q27', 'oncogene', 'T-cell growth factor'),
('IL6ST', 'Interleukin 6 cytokine family signal transducer', '5q11.2', 'oncogene', 'Cytokine receptor'),
('IL7R', 'Interleukin 7 receptor', '5p13.2', 'oncogene', 'Cytokine receptor'),
('INHA', 'Inhibin subunit alpha', '2q35', 'tumor_suppressor', 'TGF-β superfamily'),
('INHBA', 'Inhibin subunit beta A', '7p14.1', 'oncogene', 'TGF-β superfamily'),
('INPP4A', 'Inositol polyphosphate-4-phosphatase type I A', '2q11.2', 'tumor_suppressor', 'PI3K pathway regulation'),
('INPP4B', 'Inositol polyphosphate-4-phosphatase type II B', '4q31.21', 'tumor_suppressor', 'PI3K pathway regulation'),
('INSR', 'Insulin receptor', '19p13.2', 'oncogene', 'Receptor tyrosine kinase'),
('IRF1', 'Interferon regulatory factor 1', '5q31.1', 'tumor_suppressor', 'Transcription factor'),
('IRF2', 'Interferon regulatory factor 2', '4q35.1', 'tumor_suppressor', 'Transcription factor'),
('IRF4', 'Interferon regulatory factor 4', '6p25.3', 'oncogene', 'Transcription factor'),
('IRS1', 'Insulin receptor substrate 1', '2q36.3', 'oncogene', 'Insulin signaling'),
('IRS2', 'Insulin receptor substrate 2', '13q34', 'oncogene', 'Insulin signaling'),
('IRS4', 'Insulin receptor substrate 4', 'Xq22.3', 'oncogene', 'Insulin signaling'),

-- J genes
('JAK1', 'Janus kinase 1', '1p31.3', 'oncogene', 'JAK/STAT signaling'),
('JAK2', 'Janus kinase 2', '9p24.1', 'oncogene', 'JAK/STAT signaling'),
('JAK3', 'Janus kinase 3', '19p13.11', 'oncogene', 'JAK/STAT signaling'),
('JARID2', 'Jumonji and AT-rich interaction domain containing 2', '6p22.3', 'tumor_suppressor', 'PRC2 recruitment'),
('JUN', 'Jun proto-oncogene', '1p32.1', 'oncogene', 'AP-1 transcription factor'),

-- K genes  
('KAT6A', 'Lysine acetyltransferase 6A', '8p11.21', 'oncogene', 'Histone acetyltransferase'),
('KAT6B', 'Lysine acetyltransferase 6B', '10q22.2', 'tumor_suppressor', 'Histone acetyltransferase'),
('KDM5A', 'Lysine demethylase 5A', '12p13.33', 'tumor_suppressor', 'Histone demethylase'),
('KDM5C', 'Lysine demethylase 5C', 'Xp11.22', 'tumor_suppressor', 'Histone demethylase'),
('KDM6A', 'Lysine demethylase 6A', 'Xp11.3', 'tumor_suppressor', 'Histone H3K27 demethylase'),
('KDR', 'Kinase insert domain receptor', '4q12', 'oncogene', 'VEGFR2, angiogenesis'),
('KEAP1', 'Kelch like ECH associated protein 1', '19p13.2', 'tumor_suppressor', 'NRF2 pathway regulation'),
('KIF5B', 'Kinesin family member 5B', '10p11.22', 'oncogene', 'Motor protein, fusion partner'),
('KIT', 'KIT proto-oncogene', '4q12', 'oncogene', 'Receptor tyrosine kinase'),
('KLF4', 'KLF transcription factor 4', '9q31.2', 'tumor_suppressor', 'Transcription factor'),
('KLF5', 'KLF transcription factor 5', '13q22.1', 'oncogene', 'Transcription factor'),
('KMT2A', 'Lysine methyltransferase 2A (MLL)', '11q23.3', 'oncogene', 'H3K4 methyltransferase'),
('KMT2B', 'Lysine methyltransferase 2B', '19q13.12', 'tumor_suppressor', 'H3K4 methyltransferase'),
('KMT2C', 'Lysine methyltransferase 2C', '7q36.1', 'tumor_suppressor', 'H3K4 methyltransferase'),
('KMT2D', 'Lysine methyltransferase 2D', '12q13.12', 'tumor_suppressor', 'H3K4 methyltransferase'),
('KRAS', 'KRAS proto-oncogene', '12p12.1', 'oncogene', 'RAS family GTPase'),
('LATS1', 'Large tumor suppressor kinase 1', '6q25.1', 'tumor_suppressor', 'Hippo pathway'),
('LATS2', 'Large tumor suppressor kinase 2', '13q12.11', 'tumor_suppressor', 'Hippo pathway'),
('LCK', 'LCK proto-oncogene', '1p35.2', 'oncogene', 'Src family kinase'),
('LMO1', 'LIM domain only 1', '11p15.4', 'oncogene', 'Transcriptional cofactor'),
('LMO2', 'LIM domain only 2', '11p13', 'oncogene', 'Transcriptional cofactor'),
('LRP1B', 'LDL receptor related protein 1B', '2q22.1', 'tumor_suppressor', 'Receptor'),
('LYN', 'LYN proto-oncogene', '8q12.1', 'oncogene', 'Src family kinase'),

-- M genes
('LZTR1', 'Leucine zipper like transcription regulator 1', '22q11.21', 'tumor_suppressor', 'RAS pathway regulation'),
('MALT1', 'MALT1 paracaspase', '18q21.32', 'oncogene', 'NF-κB activation'),
('MAP2K1', 'Mitogen-activated protein kinase kinase 1 (MEK1)', '15q22.31', 'oncogene', 'MAPK pathway'),
('MAP2K2', 'Mitogen-activated protein kinase kinase 2 (MEK2)', '19p13.3', 'oncogene', 'MAPK pathway'),
('MAP2K4', 'Mitogen-activated protein kinase kinase 4', '17p12', 'tumor_suppressor', 'MAPK pathway'),
('MAP3K1', 'Mitogen-activated protein kinase kinase kinase 1', '5q11.2', 'tumor_suppressor', 'MAPK pathway'),
('MAP3K13', 'Mitogen-activated protein kinase kinase kinase 13', '3q27.2', 'tumor_suppressor', 'MAPK pathway'),
('MAP3K14', 'Mitogen-activated protein kinase kinase kinase 14', '17q21.31', 'oncogene', 'NF-κB pathway'),
('MAPK1', 'Mitogen-activated protein kinase 1 (ERK2)', '22q11.22', 'oncogene', 'MAPK pathway'),
('MAPK3', 'Mitogen-activated protein kinase 3 (ERK1)', '16p11.2', 'oncogene', 'MAPK pathway'),
('MAX', 'MYC associated factor X', '14q23.3', 'tumor_suppressor', 'MYC partner'),
('MCL1', 'MCL1 apoptosis regulator', '1q21.3', 'oncogene', 'Anti-apoptotic protein'),
('MDM2', 'MDM2 proto-oncogene', '12q15', 'oncogene', 'p53 negative regulator'),
('MDM4', 'MDM4 regulator of p53', '1q32.1', 'oncogene', 'p53 negative regulator'),
('MED12', 'Mediator complex subunit 12', 'Xq13.1', 'tumor_suppressor', 'Transcriptional mediator'),
('MEF2B', 'Myocyte enhancer factor 2B', '19p13.11', 'oncogene', 'Transcription factor'),
('MEN1', 'Menin 1', '11q13.1', 'tumor_suppressor', 'Chromatin regulation'),
('MET', 'MET proto-oncogene', '7q31.2', 'oncogene', 'Receptor tyrosine kinase'),
('MGMT', 'O-6-methylguanine-DNA methyltransferase', '10q26.3', 'tumor_suppressor', 'DNA repair'),
('MITF', 'Melanocyte inducing transcription factor', '3p13', 'oncogene', 'Transcription factor'),
('MLH1', 'MutL homolog 1', '3p22.2', 'tumor_suppressor', 'DNA mismatch repair'),
('MPL', 'MPL proto-oncogene', '1p34.2', 'oncogene', 'Thrombopoietin receptor'),
('MRE11', 'MRE11 homolog', '11q21', 'tumor_suppressor', 'DNA repair'),
('MSH2', 'MutS homolog 2', '2p21', 'tumor_suppressor', 'DNA mismatch repair'),
('MSH3', 'MutS homolog 3', '5q14.1', 'tumor_suppressor', 'DNA mismatch repair'),
('MSH6', 'MutS homolog 6', '2p16.3', 'tumor_suppressor', 'DNA mismatch repair'),
('MSI1', 'Musashi RNA binding protein 1', '12q24.31', 'oncogene', 'RNA binding protein'),
('MSI2', 'Musashi RNA binding protein 2', '17q22', 'oncogene', 'RNA binding protein'),
('MST1', 'Macrophage stimulating 1', '3p21.31', 'oncogene', 'Growth factor'),
('MST1R', 'Macrophage stimulating 1 receptor', '3p21.31', 'oncogene', 'Receptor tyrosine kinase'),
('MTOR', 'Mechanistic target of rapamycin kinase', '1p36.22', 'oncogene', 'mTOR pathway'),
('MTAP', 'Methylthioadenosine phosphorylase', '9p21.3', 'tumor_suppressor', 'Purine metabolism'),
('MUC1', 'Mucin 1', '1q22', 'oncogene', 'Cell surface glycoprotein'),
('MUC16', 'Mucin 16', '19p13.2', 'oncogene', 'CA125 antigen'),
('MUC4', 'Mucin 4', '3q29', 'oncogene', 'Cell surface glycoprotein'),
('MUTYH', 'MutY DNA glycosylase', '1p34.1', 'tumor_suppressor', 'Base excision repair'),
('MYB', 'MYB proto-oncogene', '6q23.3', 'oncogene', 'Transcription factor'),
('MYBL1', 'MYB proto-oncogene like 1', '8q13.1', 'oncogene', 'Transcription factor'),
('MYC', 'MYC proto-oncogene', '8q24.21', 'oncogene', 'Transcription factor'),
('MYCL', 'MYCL proto-oncogene', '1p34.2', 'oncogene', 'Transcription factor'),
('MYCN', 'MYCN proto-oncogene', '2p24.3', 'oncogene', 'Transcription factor'),
('MYD88', 'MYD88 innate immune signal transduction adaptor', '3p22.2', 'oncogene', 'TLR/IL-1R signaling'),
('MYH11', 'Myosin heavy chain 11', '16p13.11', 'tumor_suppressor', 'Smooth muscle myosin'),
('MYH9', 'Myosin heavy chain 9', '22q12.3', 'tumor_suppressor', 'Non-muscle myosin'),
('MYO5A', 'Myosin VA', '15q21.2', 'tumor_suppressor', 'Motor protein'),

-- N genes
('NAB2', 'NGFI-A binding protein 2', '12q13.3', 'tumor_suppressor', 'Transcriptional corepressor'),
('NBEA', 'Neurobeachin', '13q13.3', 'tumor_suppressor', 'Protein kinase A anchoring'),
('NBN', 'Nibrin', '8q21.3', 'tumor_suppressor', 'DNA repair'),
('NCOA1', 'Nuclear receptor coactivator 1', '2p23.3', 'oncogene', 'Transcriptional coactivator'),
('NCOA2', 'Nuclear receptor coactivator 2', '8q13.3', 'oncogene', 'Transcriptional coactivator'),
('NCOA3', 'Nuclear receptor coactivator 3', '20q13.12', 'oncogene', 'Transcriptional coactivator'),
('NCOR1', 'Nuclear receptor corepressor 1', '17p11.2', 'tumor_suppressor', 'Transcriptional corepressor'),
('NCOR2', 'Nuclear receptor corepressor 2', '12q24.31', 'tumor_suppressor', 'Transcriptional corepressor'),
('NEGR1', 'Neuronal growth regulator 1', '1p31.1', 'tumor_suppressor', 'Cell adhesion'),
('NF1', 'Neurofibromin 1', '17q11.2', 'tumor_suppressor', 'RAS GAP'),
('NF2', 'Neurofibromin 2 (merlin)', '22q12.2', 'tumor_suppressor', 'Hippo pathway'),
('NFE2L2', 'NFE2 like bZIP transcription factor 2 (NRF2)', '2q31.2', 'oncogene', 'Oxidative stress response'),
('NFIB', 'Nuclear factor I B', '9p23', 'oncogene', 'Transcription factor'),
('NFKB1', 'Nuclear factor kappa B subunit 1', '4q24', 'oncogene', 'NF-κB transcription factor'),
('NFKB2', 'Nuclear factor kappa B subunit 2', '10q24.32', 'oncogene', 'NF-κB transcription factor'),
('NFKBIA', 'NFKB inhibitor alpha', '14q13.2', 'tumor_suppressor', 'NF-κB inhibitor'),
('NIN', 'Ninein', '14q22.1', 'tumor_suppressor', 'Centrosome protein'),
('NKX2-1', 'NK2 homeobox 1', '14q13.3', 'oncogene', 'Lung lineage transcription factor'),
('NKX3-1', 'NK3 homeobox 1', '8p21.2', 'tumor_suppressor', 'Prostate transcription factor'),
('NOTCH1', 'Notch receptor 1', '9q34.3', 'context', 'Notch signaling'),
('NOTCH2', 'Notch receptor 2', '1p12', 'context', 'Notch signaling'),
('NOTCH3', 'Notch receptor 3', '19p13.12', 'oncogene', 'Notch signaling'),
('NOTCH4', 'Notch receptor 4', '6p21.32', 'oncogene', 'Notch signaling'),
('NPM1', 'Nucleophosmin 1', '5q35.1', 'oncogene', 'Nucleolar protein'),
('NR4A3', 'Nuclear receptor subfamily 4 group A member 3', '9q31.1', 'oncogene', 'Nuclear receptor'),
('NRAS', 'NRAS proto-oncogene', '1p13.2', 'oncogene', 'RAS family GTPase'),
('NRG1', 'Neuregulin 1', '8p12', 'oncogene', 'Growth factor'),
('NSD1', 'Nuclear receptor binding SET domain protein 1', '5q35.3', 'tumor_suppressor', 'H3K36 methyltransferase'),
('NSD2', 'Nuclear receptor binding SET domain protein 2', '4p16.3', 'oncogene', 'H3K36 methyltransferase'),
('NSD3', 'Nuclear receptor binding SET domain protein 3', '8p11.23', 'oncogene', 'H3K36 methyltransferase'),
('NT5C2', '5-nucleotidase cytosolic II', '10q24.32', 'oncogene', 'Nucleotide metabolism'),
('NTRK1', 'Neurotrophic receptor tyrosine kinase 1', '1q23.1', 'oncogene', 'Receptor tyrosine kinase'),
('NTRK2', 'Neurotrophic receptor tyrosine kinase 2', '9q21.33', 'oncogene', 'Receptor tyrosine kinase'),
('NTRK3', 'Neurotrophic receptor tyrosine kinase 3', '15q25.3', 'oncogene', 'Receptor tyrosine kinase'),
('NUF2', 'NDC80 kinetochore complex component', '1q25.1', 'oncogene', 'Kinetochore component'),
('NUP93', 'Nucleoporin 93', '16q13', 'tumor_suppressor', 'Nuclear pore complex'),
('NUP98', 'Nucleoporin 98', '11p15.4', 'oncogene', 'Nuclear pore, fusion partner'),
('NUTM1', 'NUT midline carcinoma family member 1', '15q14', 'oncogene', 'NUT carcinoma'),

-- P genes
('P2RY8', 'Purinergic receptor P2Y8', 'Xp22.33', 'tumor_suppressor', 'GPCR'),
('PALB2', 'Partner and localizer of BRCA2', '16p12.2', 'tumor_suppressor', 'DNA repair'),
('PALLD', 'Palladin', '4q32.3', 'tumor_suppressor', 'Cytoskeleton'),
('PARK2', 'Parkin RBR E3 ubiquitin protein ligase', '6q26', 'tumor_suppressor', 'E3 ubiquitin ligase'),
('PARP1', 'Poly(ADP-ribose) polymerase 1', '1q42.12', 'oncogene', 'DNA repair'),
('PAX3', 'Paired box 3', '2q36.1', 'oncogene', 'Transcription factor'),
('PAX5', 'Paired box 5', '9p13.2', 'tumor_suppressor', 'B-cell transcription factor'),
('PAX7', 'Paired box 7', '1p36.13', 'oncogene', 'Transcription factor'),
('PAX8', 'Paired box 8', '2q14.1', 'oncogene', 'Transcription factor'),
('PBRM1', 'Polybromo 1', '3p21.1', 'tumor_suppressor', 'SWI/SNF chromatin remodeling'),
('PBX1', 'PBX homeobox 1', '1q23.3', 'oncogene', 'HOX cofactor'),
('PCBP1', 'Poly(rC) binding protein 1', '2p13.3', 'tumor_suppressor', 'RNA binding'),
('PDCD1', 'Programmed cell death 1 (PD-1)', '2q37.3', 'tumor_suppressor', 'Immune checkpoint'),
('PDCD1LG2', 'Programmed cell death 1 ligand 2 (PD-L2)', '9p24.1', 'oncogene', 'Immune checkpoint ligand'),
('PDGFB', 'Platelet derived growth factor subunit B', '22q13.1', 'oncogene', 'Growth factor'),
('PDGFRA', 'Platelet derived growth factor receptor alpha', '4q12', 'oncogene', 'Receptor tyrosine kinase'),
('PDGFRB', 'Platelet derived growth factor receptor beta', '5q32', 'oncogene', 'Receptor tyrosine kinase'),
('PDK1', 'Pyruvate dehydrogenase kinase 1', '2q31.1', 'oncogene', 'Metabolic regulation'),
('PGR', 'Progesterone receptor', '11q22.1', 'oncogene', 'Nuclear hormone receptor'),
('PHF6', 'PHD finger protein 6', 'Xq26.2', 'tumor_suppressor', 'Chromatin regulation'),
('PHOX2B', 'Paired like homeobox 2B', '4p13', 'tumor_suppressor', 'Transcription factor'),
('PIK3C2B', 'Phosphatidylinositol-4-phosphate 3-kinase C2 beta', '1q32.1', 'tumor_suppressor', 'PI3K pathway'),
('PIK3C3', 'Phosphatidylinositol 3-kinase catalytic subunit type 3', '18q12.3', 'tumor_suppressor', 'Autophagy'),
('PIK3CA', 'Phosphatidylinositol-3-kinase catalytic alpha', '3q26.32', 'oncogene', 'PI3K/AKT pathway'),
('PIK3CB', 'Phosphatidylinositol-3-kinase catalytic beta', '3q22.3', 'oncogene', 'PI3K/AKT pathway'),
('PIK3CD', 'Phosphatidylinositol-3-kinase catalytic delta', '1p36.22', 'oncogene', 'PI3K/AKT pathway'),
('PIK3CG', 'Phosphatidylinositol-3-kinase catalytic gamma', '7q22.3', 'oncogene', 'PI3K/AKT pathway'),
('PIK3R1', 'Phosphoinositide-3-kinase regulatory subunit 1', '5q13.1', 'tumor_suppressor', 'PI3K regulation'),
('PIK3R2', 'Phosphoinositide-3-kinase regulatory subunit 2', '19q13.2', 'oncogene', 'PI3K regulation'),
('PIK3R3', 'Phosphoinositide-3-kinase regulatory subunit 3', '1p34.1', 'oncogene', 'PI3K regulation'),
('PIM1', 'Pim-1 proto-oncogene', '6p21.2', 'oncogene', 'Serine/threonine kinase'),
('PLCG1', 'Phospholipase C gamma 1', '20q12', 'oncogene', 'Signal transduction'),
('PLK2', 'Polo like kinase 2', '5q11.2', 'tumor_suppressor', 'Cell cycle kinase'),
('PMAIP1', 'Phorbol-12-myristate-13-acetate-induced protein 1', '18q21.32', 'tumor_suppressor', 'Pro-apoptotic NOXA'),
('PML', 'PML nuclear body scaffold', '15q24.1', 'tumor_suppressor', 'PML-RARA fusion'),
('PMS1', 'PMS1 homolog 1', '2q32.2', 'tumor_suppressor', 'DNA mismatch repair'),
('PMS2', 'PMS1 homolog 2', '7p22.1', 'tumor_suppressor', 'DNA mismatch repair'),
('PNRC1', 'Proline rich nuclear receptor coactivator 1', '6q15', 'tumor_suppressor', 'Nuclear receptor coactivator'),
('POLD1', 'DNA polymerase delta 1', '19q13.33', 'tumor_suppressor', 'DNA replication'),
('POLE', 'DNA polymerase epsilon', '12q24.33', 'tumor_suppressor', 'DNA replication'),
('POLQ', 'DNA polymerase theta', '3q13.33', 'oncogene', 'Error-prone DNA repair'),
('POT1', 'Protection of telomeres 1', '7q31.33', 'tumor_suppressor', 'Telomere protection'),
('POU2AF1', 'POU class 2 homeobox associating factor 1', '11q23.1', 'oncogene', 'Transcriptional coactivator'),
('POU2F2', 'POU class 2 homeobox 2', '19q13.2', 'oncogene', 'Transcription factor'),
('POU5F1', 'POU class 5 homeobox 1 (OCT4)', '6p21.33', 'oncogene', 'Pluripotency factor'),
('PPARG', 'Peroxisome proliferator activated receptor gamma', '3p25.2', 'tumor_suppressor', 'Nuclear receptor'),
('PPM1D', 'Protein phosphatase Mg2+/Mn2+ dependent 1D', '17q23.2', 'oncogene', 'p53 pathway regulation'),
('PPP2R1A', 'Protein phosphatase 2 scaffold subunit A alpha', '19q13.41', 'tumor_suppressor', 'PP2A phosphatase'),
('PPP6C', 'Protein phosphatase 6 catalytic subunit', '9q33.3', 'tumor_suppressor', 'Protein phosphatase'),
('PRDM1', 'PR/SET domain 1', '6q21', 'tumor_suppressor', 'Transcriptional repressor'),
('PRDM10', 'PR/SET domain 10', '11q24.3', 'tumor_suppressor', 'Transcriptional regulator'),
('PRDM14', 'PR/SET domain 14', '8q13.3', 'oncogene', 'Pluripotency factor'),
('PRDM16', 'PR/SET domain 16', '1p36.32', 'oncogene', 'Transcriptional regulator'),
('PRDM2', 'PR/SET domain 2', '1p36.21', 'tumor_suppressor', 'Histone methyltransferase'),
('PRDM9', 'PR/SET domain 9', '5p14.1', 'tumor_suppressor', 'Meiotic recombination'),
('PREX2', 'Phosphatidylinositol-3,4,5-trisphosphate dependent Rac exchange factor 2', '8q13.2', 'oncogene', 'GEF for RAC'),
('PRKAR1A', 'Protein kinase cAMP-dependent type I regulatory subunit alpha', '17q24.2', 'tumor_suppressor', 'PKA regulation'),
('PRKCI', 'Protein kinase C iota', '3q26.2', 'oncogene', 'Atypical PKC'),
('PRKN', 'Parkin RBR E3 ubiquitin protein ligase', '6q26', 'tumor_suppressor', 'E3 ubiquitin ligase'),
('PRSS1', 'Serine protease 1', '7q34', 'oncogene', 'Trypsinogen'),
('PRSS8', 'Serine protease 8', '16p11.2', 'tumor_suppressor', 'Serine protease'),
('PTCH1', 'Patched 1', '9q22.32', 'tumor_suppressor', 'Hedgehog pathway'),
('PTCH2', 'Patched 2', '1p34.1', 'tumor_suppressor', 'Hedgehog pathway'),
('PTEN', 'Phosphatase and tensin homolog', '10q23.31', 'tumor_suppressor', 'PI3K/AKT antagonist'),
('PTK2', 'Protein tyrosine kinase 2 (FAK)', '8q24.3', 'oncogene', 'Focal adhesion kinase'),
('PTK6', 'Protein tyrosine kinase 6', '20q13.33', 'oncogene', 'Non-receptor tyrosine kinase'),
('PTPN11', 'Protein tyrosine phosphatase non-receptor type 11', '12q24.13', 'oncogene', 'SHP2 phosphatase'),
('PTPN13', 'Protein tyrosine phosphatase non-receptor type 13', '4q21.3', 'tumor_suppressor', 'Protein phosphatase'),
('PTPN14', 'Protein tyrosine phosphatase non-receptor type 14', '1q41', 'tumor_suppressor', 'Hippo pathway'),
('PTPRD', 'Protein tyrosine phosphatase receptor type D', '9p24.1', 'tumor_suppressor', 'Receptor phosphatase'),
('PTPRS', 'Protein tyrosine phosphatase receptor type S', '19p13.3', 'tumor_suppressor', 'Receptor phosphatase'),
('PTPRT', 'Protein tyrosine phosphatase receptor type T', '20q12', 'tumor_suppressor', 'Receptor phosphatase'),
('PVT1', 'Pvt1 oncogene', '8q24.21', 'oncogene', 'Long non-coding RNA'),

-- Q genes
('QKI', 'QKI, KH domain containing RNA binding', '6q26', 'tumor_suppressor', 'RNA binding protein'),

-- R genes
('RAC1', 'Rac family small GTPase 1', '7p22.1', 'oncogene', 'Rho family GTPase'),
('RAD21', 'RAD21 cohesin complex component', '8q24.11', 'oncogene', 'Cohesin complex'),
('RAD50', 'RAD50 double strand break repair protein', '5q31.1', 'tumor_suppressor', 'DNA repair'),
('RAD51', 'RAD51 recombinase', '15q15.1', 'tumor_suppressor', 'Homologous recombination'),
('RAD51B', 'RAD51 paralog B', '14q24.1', 'tumor_suppressor', 'Homologous recombination'),
('RAD51C', 'RAD51 paralog C', '17q22', 'tumor_suppressor', 'Homologous recombination'),
('RAD51D', 'RAD51 paralog D', '17q12', 'tumor_suppressor', 'Homologous recombination'),
('RAD52', 'RAD52 homolog', '12p13.33', 'tumor_suppressor', 'DNA repair'),
('RAD54L', 'RAD54 like', '1p34.1', 'tumor_suppressor', 'DNA repair'),
('RAF1', 'Raf-1 proto-oncogene', '3p25.2', 'oncogene', 'RAF kinase'),
('RANBP2', 'RAN binding protein 2', '2q13', 'tumor_suppressor', 'Nuclear pore complex'),
('RARA', 'Retinoic acid receptor alpha', '17q21.2', 'oncogene', 'Nuclear receptor, PML-RARA'),
('RASA1', 'RAS p21 protein activator 1', '5q14.3', 'tumor_suppressor', 'RAS GAP'),
('RB1', 'RB transcriptional corepressor 1', '13q14.2', 'tumor_suppressor', 'Cell cycle checkpoint'),
('RBM10', 'RNA binding motif protein 10', 'Xp11.3', 'tumor_suppressor', 'RNA splicing'),
('RBM15', 'RNA binding motif protein 15', '1p13.3', 'oncogene', 'RNA metabolism'),
('RECQL', 'RecQ like helicase', '12p12.1', 'tumor_suppressor', 'DNA helicase'),
('RECQL4', 'RecQ like helicase 4', '8q24.3', 'tumor_suppressor', 'DNA helicase'),
('REL', 'REL proto-oncogene', '2p16.1', 'oncogene', 'NF-κB family'),
('RELA', 'RELA proto-oncogene', '11q13.1', 'oncogene', 'NF-κB p65'),
('RET', 'Ret proto-oncogene', '10q11.21', 'oncogene', 'Receptor tyrosine kinase'),
('RFWD2', 'Ring finger and WD repeat domain 2', '1q25.2', 'tumor_suppressor', 'E3 ubiquitin ligase'),
('RHEB', 'Ras homolog enriched in brain', '7q36.1', 'oncogene', 'mTOR activation'),
('RHOA', 'Ras homolog family member A', '3p21.31', 'oncogene', 'Rho GTPase'),
('RICTOR', 'RPTOR independent companion of MTOR complex 2', '5p13.1', 'oncogene', 'mTORC2 component'),
('RIT1', 'Ras like without CAAX 1', '1q22', 'oncogene', 'RAS family'),
('RNF43', 'Ring finger protein 43', '17q22', 'tumor_suppressor', 'E3 ubiquitin ligase'),
('ROS1', 'ROS proto-oncogene 1', '6q22.1', 'oncogene', 'Receptor tyrosine kinase'),
('RPA1', 'Replication protein A1', '17p13.3', 'tumor_suppressor', 'DNA replication/repair'),
('RPL10', 'Ribosomal protein L10', 'Xq28', 'tumor_suppressor', 'Ribosome'),
('RPL22', 'Ribosomal protein L22', '1p36.31', 'tumor_suppressor', 'Ribosome'),
('RPL5', 'Ribosomal protein L5', '1p22.1', 'tumor_suppressor', 'Ribosome, MDM2 binding'),
('RPS15', 'Ribosomal protein S15', '19p13.3', 'tumor_suppressor', 'Ribosome'),
('RPS6KA4', 'Ribosomal protein S6 kinase A4', '11q13.1', 'tumor_suppressor', 'RSK family kinase'),
('RPS6KB1', 'Ribosomal protein S6 kinase B1', '17q23.1', 'oncogene', 'mTOR target'),
('RPS6KB2', 'Ribosomal protein S6 kinase B2', '11q13.2', 'oncogene', 'mTOR target'),
('RPTOR', 'Regulatory associated protein of MTOR complex 1', '17q25.3', 'oncogene', 'mTORC1 component'),
('RRAGC', 'Ras related GTP binding C', '1p34.3', 'oncogene', 'mTOR regulation'),
('RRAS', 'RAS related', '19q13.33', 'oncogene', 'RAS family'),
('RRAS2', 'RAS related 2', '11p15.2', 'oncogene', 'RAS family'),
('RSPO2', 'R-spondin 2', '8q23.1', 'oncogene', 'WNT pathway activation'),
('RSPO3', 'R-spondin 3', '6q22.33', 'oncogene', 'WNT pathway activation'),
('RTEL1', 'Regulator of telomere elongation helicase 1', '20q13.33', 'tumor_suppressor', 'Telomere maintenance'),
('RUNX1', 'RUNX family transcription factor 1', '21q22.12', 'tumor_suppressor', 'Hematopoietic transcription factor'),
('RUNX1T1', 'RUNX1 partner transcriptional co-repressor 1', '8q21.3', 'oncogene', 'RUNX1-RUNX1T1 fusion'),
('RXRA', 'Retinoid X receptor alpha', '9q34.2', 'tumor_suppressor', 'Nuclear receptor'),

-- S genes
('S1PR2', 'Sphingosine-1-phosphate receptor 2', '19p13.2', 'tumor_suppressor', 'GPCR'),
('SALL4', 'Spalt like transcription factor 4', '20q13.2', 'oncogene', 'Stem cell factor'),
('SAMHD1', 'SAM and HD domain containing deoxynucleoside triphosphate triphosphohydrolase 1', '20q11.23', 'tumor_suppressor', 'dNTP metabolism'),
('SBDS', 'SBDS ribosome assembly guanine nucleotide exchange factor', '7q11.21', 'tumor_suppressor', 'Ribosome biogenesis'),
('SCAF4', 'SR-related CTD associated factor 4', '21q22.3', 'tumor_suppressor', 'RNA splicing'),
('SDHAF2', 'Succinate dehydrogenase complex assembly factor 2', '11q12.2', 'tumor_suppressor', 'SDH assembly'),
('SDHB', 'Succinate dehydrogenase complex subunit B', '1p36.13', 'tumor_suppressor', 'TCA cycle'),
('SDHC', 'Succinate dehydrogenase complex subunit C', '1q23.3', 'tumor_suppressor', 'TCA cycle'),
('SDHD', 'Succinate dehydrogenase complex subunit D', '11q23.1', 'tumor_suppressor', 'TCA cycle'),
('SERPINB3', 'Serpin family B member 3', '18q21.33', 'oncogene', 'Protease inhibitor'),
('SERPINB4', 'Serpin family B member 4', '18q21.33', 'oncogene', 'Protease inhibitor'),
('SESN1', 'Sestrin 1', '6q21', 'tumor_suppressor', 'mTOR regulation'),
('SESN2', 'Sestrin 2', '1p35.3', 'tumor_suppressor', 'mTOR regulation'),
('SESN3', 'Sestrin 3', '11q21', 'tumor_suppressor', 'mTOR regulation'),
('SETBP1', 'SET binding protein 1', '18q12.3', 'oncogene', 'SET regulation'),
('SETD1A', 'SET domain containing 1A', '16p11.2', 'tumor_suppressor', 'H3K4 methyltransferase'),
('SETD1B', 'SET domain containing 1B', '12q24.31', 'tumor_suppressor', 'H3K4 methyltransferase'),
('SETD2', 'SET domain containing 2', '3p21.31', 'tumor_suppressor', 'H3K36 methyltransferase'),
('SETDB1', 'SET domain bifurcated histone lysine methyltransferase 1', '1q21.3', 'oncogene', 'H3K9 methyltransferase'),
('SF3B1', 'Splicing factor 3b subunit 1', '2q33.1', 'oncogene', 'RNA splicing'),
('SH2B3', 'SH2B adaptor protein 3', '12q24.12', 'tumor_suppressor', 'Cytokine signaling'),
('SH2D1A', 'SH2 domain containing 1A', 'Xq25', 'tumor_suppressor', 'T-cell signaling'),
('SHOC2', 'SHOC2 leucine rich repeat scaffold protein', '10q25.2', 'oncogene', 'RAS pathway'),
('SHQ1', 'SHQ1 H/ACA ribonucleoprotein assembly factor', '3p13', 'tumor_suppressor', 'Telomerase biogenesis'),
('SIK1', 'Salt inducible kinase 1', '21q22.3', 'tumor_suppressor', 'AMPK family kinase'),
('SIN3A', 'SIN3 transcription regulator family member A', '15q24.2', 'tumor_suppressor', 'Transcriptional corepressor'),
('SIRT2', 'Sirtuin 2', '19q13.2', 'tumor_suppressor', 'NAD-dependent deacetylase'),
('SIX1', 'SIX homeobox 1', '14q23.1', 'oncogene', 'Transcription factor'),
('SIX2', 'SIX homeobox 2', '2p21', 'oncogene', 'Transcription factor'),
('SKI', 'SKI proto-oncogene', '1p36.33', 'oncogene', 'TGF-β pathway'),
('SLC34A2', 'Solute carrier family 34 member 2', '4p15.2', 'tumor_suppressor', 'Phosphate transporter'),
('SLC45A3', 'Solute carrier family 45 member 3', '1q32.1', 'oncogene', 'Sugar transporter'),
('SMAD2', 'SMAD family member 2', '18q21.1', 'tumor_suppressor', 'TGF-β signaling'),
('SMAD3', 'SMAD family member 3', '15q22.33', 'tumor_suppressor', 'TGF-β signaling'),
('SMAD4', 'SMAD family member 4', '18q21.2', 'tumor_suppressor', 'TGF-β signaling'),
('SMARCA2', 'SWI/SNF related matrix associated actin dependent regulator of chromatin a2', '9p24.3', 'tumor_suppressor', 'SWI/SNF complex'),
('SMARCA4', 'SWI/SNF related matrix associated actin dependent regulator of chromatin a4', '19p13.2', 'tumor_suppressor', 'SWI/SNF complex'),
('SMARCB1', 'SWI/SNF related matrix associated actin dependent regulator of chromatin b1', '22q11.23', 'tumor_suppressor', 'SWI/SNF complex'),
('SMARCD1', 'SWI/SNF related matrix associated actin dependent regulator of chromatin d1', '12q13.12', 'tumor_suppressor', 'SWI/SNF complex'),
('SMARCE1', 'SWI/SNF related matrix associated actin dependent regulator of chromatin e1', '17q21.2', 'tumor_suppressor', 'SWI/SNF complex'),
('SMC1A', 'Structural maintenance of chromosomes 1A', 'Xp11.22', 'tumor_suppressor', 'Cohesin complex'),
('SMC3', 'Structural maintenance of chromosomes 3', '10q25.2', 'tumor_suppressor', 'Cohesin complex'),
('SMO', 'Smoothened, frizzled class receptor', '7q32.1', 'oncogene', 'Hedgehog pathway'),
('SNCAIP', 'Synuclein alpha interacting protein', '5q23.2', 'tumor_suppressor', 'Unknown function'),
('SND1', 'Staphylococcal nuclease and tudor domain containing 1', '7q31.33', 'oncogene', 'Transcriptional coactivator'),
('SNX29', 'Sorting nexin 29', '16p13.13', 'tumor_suppressor', 'Protein trafficking'),
('SOCS1', 'Suppressor of cytokine signaling 1', '16p13.13', 'tumor_suppressor', 'JAK/STAT inhibitor'),
('SOX10', 'SRY-box transcription factor 10', '22q13.1', 'oncogene', 'Neural crest transcription factor'),
('SOX17', 'SRY-box transcription factor 17', '8q11.23', 'tumor_suppressor', 'Transcription factor'),
('SOX2', 'SRY-box transcription factor 2', '3q26.33', 'oncogene', 'Pluripotency factor'),
('SOX21', 'SRY-box transcription factor 21', '13q32.1', 'tumor_suppressor', 'Transcription factor'),
('SOX9', 'SRY-box transcription factor 9', '17q24.3', 'oncogene', 'Transcription factor'),
('SPEN', 'Spen family transcriptional repressor', '1p36.21', 'tumor_suppressor', 'Transcriptional corepressor'),
('SPOP', 'Speckle type BTB/POZ protein', '17q21.33', 'tumor_suppressor', 'E3 ubiquitin ligase adaptor'),
('SPRED1', 'Sprouty related EVH1 domain containing 1', '15q14', 'tumor_suppressor', 'RAS/MAPK inhibitor'),
('SPT16', 'SPT16 homolog', '11q12.1', 'oncogene', 'FACT complex'),
('SPTA1', 'Spectrin alpha', '1q23.1', 'tumor_suppressor', 'Cytoskeleton'),
('SRC', 'SRC proto-oncogene', '20q11.23', 'oncogene', 'Non-receptor tyrosine kinase'),
('SRSF2', 'Serine and arginine rich splicing factor 2', '17q25.1', 'oncogene', 'RNA splicing'),
('SRSF3', 'Serine and arginine rich splicing factor 3', '6p21.31', 'oncogene', 'RNA splicing'),
('SS18', 'SS18 subunit of BAF chromatin remodeling complex', '18q11.2', 'oncogene', 'SWI/SNF complex, synovial sarcoma'),
('SS18L1', 'SS18 like 1', '20q13.33', 'tumor_suppressor', 'SWI/SNF complex'),
('SSX1', 'SSX family member 1', 'Xp11.23', 'oncogene', 'SS18-SSX fusion partner'),
('SSX2', 'SSX family member 2', 'Xp11.22', 'oncogene', 'SS18-SSX fusion partner'),
('SSX4', 'SSX family member 4', 'Xp11.23', 'oncogene', 'SS18-SSX fusion partner'),
('STAG1', 'Stromal antigen 1', '3q22.3', 'tumor_suppressor', 'Cohesin complex'),
('STAG2', 'Stromal antigen 2', 'Xq25', 'tumor_suppressor', 'Cohesin complex'),
('STAT3', 'Signal transducer and activator of transcription 3', '17q21.2', 'oncogene', 'JAK/STAT transcription factor'),
('STAT4', 'Signal transducer and activator of transcription 4', '2q32.3', 'tumor_suppressor', 'JAK/STAT transcription factor'),
('STAT5A', 'Signal transducer and activator of transcription 5A', '17q21.2', 'oncogene', 'JAK/STAT transcription factor'),
('STAT5B', 'Signal transducer and activator of transcription 5B', '17q21.2', 'oncogene', 'JAK/STAT transcription factor'),
('STAT6', 'Signal transducer and activator of transcription 6', '12q13.3', 'oncogene', 'JAK/STAT transcription factor'),
('STIL', 'STIL centriolar assembly protein', '1p33', 'oncogene', 'Centrosome duplication'),
('STK11', 'Serine/threonine kinase 11', '19p13.3', 'tumor_suppressor', 'LKB1, mTOR regulation'),
('STK19', 'Serine/threonine kinase 19', '6p21.33', 'tumor_suppressor', 'Protein kinase'),
('STK40', 'Serine/threonine kinase 40', '1p34.3', 'tumor_suppressor', 'Protein kinase'),
('STRN', 'Striatin', '2p22.2', 'tumor_suppressor', 'PP2A regulation'),
('SUFU', 'SUFU negative regulator of hedgehog signaling', '10q24.32', 'tumor_suppressor', 'Hedgehog pathway'),
('SUZ12', 'SUZ12 polycomb repressive complex 2 subunit', '17q11.2', 'tumor_suppressor', 'PRC2 complex'),
('SYK', 'Spleen associated tyrosine kinase', '9q22.2', 'tumor_suppressor', 'Non-receptor tyrosine kinase'),
('SYNE1', 'Spectrin repeat containing nuclear envelope protein 1', '6q25.2', 'tumor_suppressor', 'Nuclear envelope'),
('SYNGR1', 'Synaptogyrin 1', '22q13.1', 'tumor_suppressor', 'Synaptic vesicle protein'),

-- T genes
('TAF1', 'TATA-box binding protein associated factor 1', 'Xq13.1', 'tumor_suppressor', 'Transcription initiation'),
('TAF1L', 'TATA-box binding protein associated factor 1 like', '9p21.1', 'tumor_suppressor', 'Transcription initiation'),
('TAL1', 'TAL bHLH transcription factor 1', '1p33', 'oncogene', 'T-cell acute lymphoblastic leukemia'),
('TAP1', 'Transporter 1, ATP binding cassette subfamily B member', '6p21.32', 'tumor_suppressor', 'Antigen presentation'),
('TAP2', 'Transporter 2, ATP binding cassette subfamily B member', '6p21.32', 'tumor_suppressor', 'Antigen presentation'),
('TBC1D12', 'TBC1 domain family member 12', '10q23.33', 'tumor_suppressor', 'mTOR regulation'),
('TBL1XR1', 'TBL1X/Y related 1', '3q26.32', 'oncogene', 'Transcriptional corepressor'),
('TBX3', 'T-box transcription factor 3', '12q24.21', 'oncogene', 'Transcription factor'),
('TCEA1', 'Transcription elongation factor A1', '8q11.23', 'tumor_suppressor', 'Transcription elongation'),
('TCEB1', 'Elongin C', '8q21.11', 'tumor_suppressor', 'VHL complex'),
('TCF3', 'Transcription factor 3', '19p13.3', 'tumor_suppressor', 'E2A, B-cell development'),
('TCF7', 'Transcription factor 7', '5q31.1', 'tumor_suppressor', 'WNT pathway'),
('TCF7L1', 'Transcription factor 7 like 1', '2p11.2', 'tumor_suppressor', 'WNT pathway'),
('TCF7L2', 'Transcription factor 7 like 2', '10q25.2', 'tumor_suppressor', 'WNT pathway'),
('TCL1A', 'TCL1 family AKT coactivator A', '14q32.13', 'oncogene', 'AKT activation'),
('TET1', 'Tet methylcytosine dioxygenase 1', '10q21.3', 'tumor_suppressor', 'DNA demethylation'),
('TET2', 'Tet methylcytosine dioxygenase 2', '4q24', 'tumor_suppressor', 'DNA demethylation'),
('TET3', 'Tet methylcytosine dioxygenase 3', '2p13.1', 'tumor_suppressor', 'DNA demethylation'),
('TFE3', 'Transcription factor binding to IGHM enhancer 3', 'Xp11.23', 'oncogene', 'MiT family transcription factor'),
('TFEB', 'Transcription factor EB', '6p21.1', 'oncogene', 'MiT family transcription factor'),
('TFEC', 'Transcription factor EC', '7q31.2', 'oncogene', 'MiT family transcription factor'),
('TFG', 'Trafficking from ER to Golgi regulator', '3q12.2', 'oncogene', 'Protein trafficking'),
('TFPT', 'TCF3 fusion partner', '19q13.42', 'tumor_suppressor', 'Unknown function'),
('TFRC', 'Transferrin receptor', '3q29', 'oncogene', 'Iron uptake'),
('TGFB1', 'Transforming growth factor beta 1', '19q13.2', 'context', 'TGF-β signaling'),
('TGFB2', 'Transforming growth factor beta 2', '1q41', 'tumor_suppressor', 'TGF-β signaling'),
('TGFB3', 'Transforming growth factor beta 3', '14q24.3', 'tumor_suppressor', 'TGF-β signaling'),
('TGFBR1', 'Transforming growth factor beta receptor 1', '9q22.33', 'tumor_suppressor', 'TGF-β receptor'),
('TGFBR2', 'Transforming growth factor beta receptor 2', '3p24.1', 'tumor_suppressor', 'TGF-β receptor'),
('TGIF1', 'TGFB induced factor homeobox 1', '18p11.31', 'tumor_suppressor', 'TGF-β pathway regulation'),
('THRAP3', 'Thyroid hormone receptor associated protein 3', '1p34.3', 'tumor_suppressor', 'Transcriptional coactivator'),
('TIAM1', 'TIAM Rac1 associated GEF 1', '21q22.11', 'oncogene', 'RAC activation'),
('TLL2', 'Tolloid like 2', '10q24.1', 'tumor_suppressor', 'BMP processing'),
('TMEM127', 'Transmembrane protein 127', '2q11.2', 'tumor_suppressor', 'mTOR regulation'),
('TMEM30A', 'Transmembrane protein 30A', '6q14.1', 'tumor_suppressor', 'Phospholipid flippase'),
('TMPRSS2', 'Transmembrane serine protease 2', '21q22.3', 'oncogene', 'TMPRSS2-ERG fusion partner'),
('TNFAIP3', 'TNF alpha induced protein 3', '6q23.3', 'tumor_suppressor', 'A20, NF-κB regulation'),
('TNFRSF10A', 'TNF receptor superfamily member 10a', '8p21.3', 'tumor_suppressor', 'Death receptor DR4'),
('TNFRSF10B', 'TNF receptor superfamily member 10b', '8p21.3', 'tumor_suppressor', 'Death receptor DR5'),
('TNFRSF10C', 'TNF receptor superfamily member 10c', '8p21.3', 'tumor_suppressor', 'Decoy receptor DcR1'),
('TNFRSF10D', 'TNF receptor superfamily member 10d', '8p21.3', 'tumor_suppressor', 'Decoy receptor DcR2'),
('TNFRSF14', 'TNF receptor superfamily member 14', '1p36.32', 'tumor_suppressor', 'HVEM, immune regulation'),
('TNFRSF17', 'TNF receptor superfamily member 17', '16p13.13', 'oncogene', 'BCMA, B-cell survival'),
('TNK2', 'Tyrosine kinase non receptor 2', '3q29', 'oncogene', 'ACK1, non-receptor tyrosine kinase'),
('TOP1', 'DNA topoisomerase I', '20q12', 'oncogene', 'DNA topology'),
('TOP2A', 'DNA topoisomerase II alpha', '17q21.2', 'oncogene', 'DNA topology'),
('TP53', 'Tumor protein p53', '17p13.1', 'tumor_suppressor', 'Guardian of the genome'),
('TP53BP1', '53BP1, p53 binding protein 1', '15q15.3', 'tumor_suppressor', 'DNA damage response'),
('TP63', 'Tumor protein p63', '3q28', 'tumor_suppressor', 'p53 family member'),
('TPMT', 'Thiopurine S-methyltransferase', '6p22.3', 'other', 'Drug metabolism'),
('TPR', 'Translocated promoter region', '1q31.1', 'oncogene', 'Nuclear pore complex'),
('TRA', 'T-cell receptor alpha locus', '14q11.2', 'oncogene', 'T-cell receptor'),
('TRAF2', 'TNF receptor associated factor 2', '9q34.3', 'oncogene', 'NF-κB activation'),
('TRAF3', 'TNF receptor associated factor 3', '14q32.32', 'tumor_suppressor', 'NF-κB regulation'),
('TRAF5', 'TNF receptor associated factor 5', '1q32.3', 'oncogene', 'NF-κB activation'),
('TRAF7', 'TNF receptor associated factor 7', '16p13.3', 'tumor_suppressor', 'Unknown function'),
('TRB', 'T-cell receptor beta locus', '7q34', 'oncogene', 'T-cell receptor'),
('TRD', 'T-cell receptor delta locus', '14q11.2', 'oncogene', 'T-cell receptor'),
('TRG', 'T-cell receptor gamma locus', '7p14.1', 'oncogene', 'T-cell receptor'),
('TRIM24', 'Tripartite motif containing 24', '7q33', 'oncogene', 'Transcriptional coactivator'),
('TRIM27', 'Tripartite motif containing 27', '6p22.1', 'oncogene', 'E3 ubiquitin ligase'),
('TRIM33', 'Tripartite motif containing 33', '1p13.2', 'tumor_suppressor', 'TGF-β pathway'),
('TRIP11', 'Thyroid hormone receptor interactor 11', '14q32.12', 'oncogene', 'Golgi protein'),
('TRRAP', 'Transformation/transcription domain associated protein', '7q22.1', 'tumor_suppressor', 'HAT complex'),
('TSC1', 'TSC complex subunit 1', '9q34.13', 'tumor_suppressor', 'mTOR regulation'),
('TSC2', 'TSC complex subunit 2', '16p13.3', 'tumor_suppressor', 'mTOR regulation'),
('TSHR', 'Thyroid stimulating hormone receptor', '14q31.1', 'oncogene', 'GPCR'),
('TTL', 'Tubulin tyrosine ligase', '2q13', 'tumor_suppressor', 'Microtubule modification'),
('TUBB', 'Tubulin beta class I', '6p21.33', 'oncogene', 'Microtubule component'),
('TULP4', 'TUB like protein 4', '6q25.3', 'tumor_suppressor', 'Unknown function'),
('TWIST1', 'Twist family bHLH transcription factor 1', '7p21.1', 'oncogene', 'EMT transcription factor'),
('TYK2', 'Tyrosine kinase 2', '19p13.2', 'oncogene', 'JAK family kinase'),
('TYMS', 'Thymidylate synthetase', '18p11.32', 'oncogene', 'Nucleotide metabolism'),

-- U genes
('U2AF1', 'U2 small nuclear RNA auxiliary factor 1', '21q22.3', 'oncogene', 'RNA splicing'),
('U2AF2', 'U2 small nuclear RNA auxiliary factor 2', '19q13.42', 'tumor_suppressor', 'RNA splicing'),
('UBE2A', 'Ubiquitin conjugating enzyme E2 A', 'Xq24', 'tumor_suppressor', 'Ubiquitin conjugation'),
('UBE2T', 'Ubiquitin conjugating enzyme E2 T', '1q32.1', 'oncogene', 'Fanconi anemia pathway'),
('UBR5', 'Ubiquitin protein ligase E3 component n-recognin 5', '8q22.3', 'tumor_suppressor', 'E3 ubiquitin ligase'),
('UGT1A1', 'UDP glucuronosyltransferase family 1 member A1', '2q37.1', 'other', 'Drug metabolism'),
('UHRF1', 'Ubiquitin like PHD and ring finger domains 1', '19p13.3', 'oncogene', 'DNA methylation maintenance'),
('UMPS', 'Uridine 5-monophosphate synthase', '3q21.2', 'oncogene', 'Pyrimidine synthesis'),
('UPF1', 'UPF1 RNA helicase and ATPase', '19p13.11', 'tumor_suppressor', 'Nonsense-mediated decay'),
('USP28', 'Ubiquitin specific peptidase 28', '11q23.2', 'oncogene', 'Deubiquitinase'),
('USP44', 'Ubiquitin specific peptidase 44', '12q22', 'tumor_suppressor', 'Spindle checkpoint'),
('USP6', 'Ubiquitin specific peptidase 6', '17p13.2', 'oncogene', 'Deubiquitinase'),
('USP7', 'Ubiquitin specific peptidase 7', '16p13.2', 'oncogene', 'MDM2/p53 regulation'),
('USP8', 'Ubiquitin specific peptidase 8', '15q21.2', 'oncogene', 'EGFR regulation'),
('USP9X', 'Ubiquitin specific peptidase 9 X-linked', 'Xp11.4', 'tumor_suppressor', 'Deubiquitinase'),
('UTF1', 'Undifferentiated embryonic cell transcription factor 1', '10q26.3', 'tumor_suppressor', 'Pluripotency regulation'),

-- V genes
('VEGFA', 'Vascular endothelial growth factor A', '6p21.1', 'oncogene', 'Angiogenesis'),
('VEGFB', 'Vascular endothelial growth factor B', '11q13.1', 'oncogene', 'Angiogenesis'),
('VEGFC', 'Vascular endothelial growth factor C', '4q34.3', 'oncogene', 'Lymphangiogenesis'),
('VHL', 'Von Hippel-Lindau tumor suppressor', '3p25.3', 'tumor_suppressor', 'HIF regulation'),
('VTI1A', 'Vesicle transport through interaction with t-SNAREs 1A', '10q25.2', 'tumor_suppressor', 'Vesicle trafficking'),

-- W genes
('WAS', 'WASP actin nucleation promoting factor', 'Xp11.23', 'tumor_suppressor', 'Actin polymerization'),
('WDPCP', 'WD repeat containing planar cell polarity effector', '2p15', 'tumor_suppressor', 'Planar cell polarity'),
('WEE1', 'WEE1 G2 checkpoint kinase', '11p15.4', 'tumor_suppressor', 'Cell cycle checkpoint'),
('WHSC1', 'Wolf-Hirschhorn syndrome candidate 1', '4p16.3', 'oncogene', 'H3K36 methyltransferase'),
('WHSC1L1', 'WHSC1 like 1', '8p11.23', 'oncogene', 'H3K36 methyltransferase'),
('WIF1', 'WNT inhibitory factor 1', '12q14.3', 'tumor_suppressor', 'WNT antagonist'),
('WISP3', 'WNT1 inducible signaling pathway protein 3', '6q21', 'tumor_suppressor', 'WNT pathway'),
('WNK2', 'WNK lysine deficient protein kinase 2', '9q22.31', 'tumor_suppressor', 'Protein kinase'),
('WNT1', 'Wnt family member 1', '12q13.12', 'oncogene', 'WNT ligand'),
('WNT10B', 'Wnt family member 10B', '12q13.12', 'oncogene', 'WNT ligand'),
('WNT2', 'Wnt family member 2', '7q31.2', 'oncogene', 'WNT ligand'),
('WNT3', 'Wnt family member 3', '17q21.31', 'oncogene', 'WNT ligand'),
('WNT5A', 'Wnt family member 5A', '3p14.3', 'context', 'WNT ligand'),
('WNT5B', 'Wnt family member 5B', '12p13.33', 'oncogene', 'WNT ligand'),
('WRN', 'WRN RecQ like helicase', '8p12', 'tumor_suppressor', 'DNA helicase, Werner syndrome'),
('WT1', 'WT1 transcription factor', '11p13', 'tumor_suppressor', 'Wilms tumor'),
('WWOX', 'WW domain containing oxidoreductase', '16q23.1', 'tumor_suppressor', 'Oxidoreductase'),
('WWTR1', 'WW domain containing transcription regulator 1', '3q25.1', 'oncogene', 'TAZ, Hippo pathway'),

-- X genes
('XBP1', 'X-box binding protein 1', '22q12.1', 'oncogene', 'ER stress response'),
('XIAP', 'X-linked inhibitor of apoptosis', 'Xq25', 'oncogene', 'Apoptosis inhibitor'),
('XPA', 'XPA, DNA damage recognition and repair factor', '9q22.33', 'tumor_suppressor', 'Nucleotide excision repair'),
('XPC', 'XPC complex subunit', '3p25.1', 'tumor_suppressor', 'Nucleotide excision repair'),
('XPO1', 'Exportin 1', '2p15', 'oncogene', 'Nuclear export'),
('XRCC1', 'X-ray repair cross complementing 1', '19q13.31', 'tumor_suppressor', 'Base excision repair'),
('XRCC2', 'X-ray repair cross complementing 2', '7q36.1', 'tumor_suppressor', 'Homologous recombination'),
('XRCC3', 'X-ray repair cross complementing 3', '14q32.33', 'tumor_suppressor', 'Homologous recombination'),

-- Y genes
('YAP1', 'Yes1 associated transcriptional regulator', '11q22.1', 'oncogene', 'Hippo pathway effector'),
('YES1', 'YES proto-oncogene 1', '18p11.32', 'oncogene', 'Src family kinase'),
('YWHAE', '14-3-3 epsilon', '17p13.3', 'oncogene', '14-3-3 protein family'),

-- Z genes
('ZBTB16', 'Zinc finger and BTB domain containing 16', '11q23.2', 'tumor_suppressor', 'PLZF, transcription factor'),
('ZBTB2', 'Zinc finger and BTB domain containing 2', '6q25.1', 'oncogene', 'Transcription factor'),
('ZBTB20', 'Zinc finger and BTB domain containing 20', '3q13.31', 'tumor_suppressor', 'Transcription factor'),
('ZBTB7A', 'Zinc finger and BTB domain containing 7A', '19p13.3', 'oncogene', 'Transcription factor'),
('ZCCHC8', 'Zinc finger CCHC-type containing 8', '12q24.31', 'tumor_suppressor', 'RNA processing'),
('ZEB1', 'Zinc finger E-box binding homeobox 1', '10p11.22', 'oncogene', 'EMT transcription factor'),
('ZEB2', 'Zinc finger E-box binding homeobox 2', '2q22.3', 'oncogene', 'EMT transcription factor'),
('ZFHX3', 'Zinc finger homeobox 3', '16q22.3', 'tumor_suppressor', 'Transcription factor'),
('ZFHX4', 'Zinc finger homeobox 4', '8q21.11', 'tumor_suppressor', 'Transcription factor'),
('ZFP36L1', 'ZFP36 ring finger protein like 1', '14q24.1', 'tumor_suppressor', 'mRNA stability'),
('ZFP36L2', 'ZFP36 ring finger protein like 2', '2p21', 'tumor_suppressor', 'mRNA stability'),
('ZFPM1', 'Zinc finger protein multitype 1', '16q24.2', 'tumor_suppressor', 'FOG1, transcriptional cofactor'),
('ZMYM2', 'Zinc finger MYM-type containing 2', '13q12.11', 'tumor_suppressor', 'Transcriptional repressor'),
('ZMYM3', 'Zinc finger MYM-type containing 3', 'Xq13.1', 'tumor_suppressor', 'Transcriptional repressor'),
('ZNF217', 'Zinc finger protein 217', '20q13.2', 'oncogene', 'Transcription factor'),
('ZNF331', 'Zinc finger protein 331', '19q13.42', 'tumor_suppressor', 'Transcription factor'),
('ZNF384', 'Zinc finger protein 384', '12p13.31', 'oncogene', 'Transcription factor, fusion partner'),
('ZNF471', 'Zinc finger protein 471', '19q13.43', 'tumor_suppressor', 'Transcription factor'),
('ZNF521', 'Zinc finger protein 521', '18q11.2', 'oncogene', 'Transcription factor'),
('ZNF703', 'Zinc finger protein 703', '8p11.23', 'oncogene', 'Transcription factor'),
('ZNF750', 'Zinc finger protein 750', '17q25.3', 'tumor_suppressor', 'Epidermal differentiation'),
('ZNRF3', 'Zinc and ring finger 3', '22q12.1', 'tumor_suppressor', 'WNT pathway regulation'),
('ZRSR2', 'Zinc finger CCCH-type RNA binding motif and serine/arginine rich 2', 'Xp22.2', 'tumor_suppressor', 'RNA splicing'),
('ZZEF1', 'Zinc finger ZZ-type and EF-hand domain containing 1', '17p13.2', 'tumor_suppressor', 'Unknown function');

-- ==========================================
-- COMPREHENSIVE MUTATIONS (Based on COSMIC, OncoKB)
-- ==========================================
INSERT INTO mutations (gene_id, position, mutation_type, cancer_type_id, amino_acid_change, clinical_significance, mutation_count, frequency) VALUES
-- TP53 mutations (most frequent tumor suppressor mutations across cancers)
(1, 175, 'missense', 1, 'R175H', 'Pathogenic', 1245, 0.08),
(1, 248, 'missense', 1, 'R248W', 'Pathogenic', 987, 0.06),
(1, 273, 'missense', 1, 'R273H', 'Pathogenic', 1156, 0.07),
(1, 282, 'missense', 1, 'R282W', 'Pathogenic', 743, 0.045),
(1, 175, 'missense', 2, 'R175H', 'Pathogenic', 2341, 0.12),
(1, 248, 'missense', 2, 'R248Q', 'Pathogenic', 1876, 0.095),
(1, 273, 'missense', 2, 'R273C', 'Pathogenic', 2123, 0.11),
(1, 175, 'missense', 3, 'R175H', 'Pathogenic', 1534, 0.09),
(1, 248, 'missense', 3, 'R248W', 'Pathogenic', 1287, 0.075),
(1, 220, 'missense', 8, 'Y220C', 'Pathogenic', 987, 0.14),
(1, 245, 'missense', 8, 'G245S', 'Pathogenic', 654, 0.095),

-- KRAS mutations (most common oncogene mutations in solid tumors)
(360, 12, 'missense', 3, 'G12D', 'Pathogenic', 3456, 0.45),
(360, 12, 'missense', 3, 'G12V', 'Pathogenic', 2987, 0.38),
(360, 12, 'missense', 3, 'G12C', 'Pathogenic', 1876, 0.24),
(360, 13, 'missense', 3, 'G13D', 'Pathogenic', 1234, 0.16),
(360, 61, 'missense', 3, 'Q61H', 'Pathogenic', 876, 0.11),
(360, 12, 'missense', 29, 'G12D', 'Pathogenic', 1987, 0.32),
(360, 12, 'missense', 29, 'G12V', 'Pathogenic', 1654, 0.27),
(360, 12, 'missense', 1, 'G12C', 'Pathogenic', 2341, 0.18),
(360, 12, 'missense', 1, 'G12D', 'Pathogenic', 1876, 0.14),
(360, 146, 'missense', 1, 'A146T', 'Pathogenic', 543, 0.04),

-- EGFR mutations (major lung cancer driver)
(85, 858, 'missense', 1, 'L858R', 'Pathogenic', 4567, 0.28),
(85, 790, 'missense', 1, 'T790M', 'Pathogenic', 2987, 0.18),
(85, 746, 'deletion', 1, 'E746_A750del', 'Pathogenic', 5234, 0.32),
(85, 861, 'missense', 1, 'L861Q', 'Pathogenic', 987, 0.06),
(85, 719, 'insertion', 1, 'G719S', 'Pathogenic', 654, 0.04),
(85, 773, 'insertion', 1, 'H773_V774insNPH', 'Pathogenic', 432, 0.03),

-- PIK3CA mutations (common in multiple cancers)
(527, 542, 'missense', 2, 'E542K', 'Pathogenic', 1876, 0.15),
(527, 545, 'missense', 2, 'E545K', 'Pathogenic', 2341, 0.19),
(527, 1047, 'missense', 2, 'H1047R', 'Pathogenic', 2987, 0.24),
(527, 1047, 'missense', 7, 'H1047R', 'Pathogenic', 1234, 0.16),
(527, 542, 'missense', 7, 'E542K', 'Pathogenic', 987, 0.13),
(527, 546, 'missense', 74, 'E546K', 'Pathogenic', 543, 0.11),

-- BRAF mutations (melanoma and other cancers)
(59, 600, 'missense', 27, 'V600E', 'Pathogenic', 8765, 0.85),
(59, 600, 'missense', 27, 'V600K', 'Pathogenic', 1234, 0.12),
(59, 600, 'missense', 1, 'V600E', 'Pathogenic', 987, 0.08),
(59, 469, 'missense', 27, 'G469A', 'Pathogenic', 456, 0.04),
(59, 600, 'missense', 35, 'V600E', 'Pathogenic', 2341, 0.67),

-- NRAS mutations (melanoma)
(471, 61, 'missense', 27, 'Q61R', 'Pathogenic', 2345, 0.22),
(471, 61, 'missense', 27, 'Q61K', 'Pathogenic', 1876, 0.18),
(471, 12, 'missense', 27, 'G12D', 'Pathogenic', 987, 0.09),

-- IDH1/IDH2 mutations (gliomas and hematologic malignancies)
(314, 132, 'missense', 33, 'R132H', 'Pathogenic', 5432, 0.78),
(314, 132, 'missense', 33, 'R132C', 'Pathogenic', 876, 0.13),
(314, 132, 'missense', 33, 'R132G', 'Pathogenic', 543, 0.08),
(315, 140, 'missense', 33, 'R140Q', 'Pathogenic', 2341, 0.34),
(315, 172, 'missense', 33, 'R172K', 'Pathogenic', 1876, 0.27),

-- BRCA1/BRCA2 mutations (breast/ovarian cancer)
(60, 1775, 'nonsense', 24, 'R1775*', 'Pathogenic', 1234, 0.18),
(60, 5382, 'frameshift', 24, '5382insC', 'Pathogenic', 987, 0.14),
(60, 185, 'nonsense', 24, 'Q185*', 'Pathogenic', 654, 0.09),
(60, 1775, 'nonsense', 31, 'R1775*', 'Pathogenic', 543, 0.12),
(61, 6174, 'frameshift', 24, '6174delT', 'Pathogenic', 876, 0.13),
(61, 999, 'nonsense', 24, 'S999*', 'Pathogenic', 432, 0.06),

-- ALK fusions (lung cancer and lymphomas)
(95, 1, 'fusion', 1, 'EML4-ALK', 'Pathogenic', 2987, 0.05),
(95, 1, 'fusion', 1, 'NPM1-ALK', 'Pathogenic', 543, 0.01),
(95, 1, 'fusion', 52, 'NPM1-ALK', 'Pathogenic', 1876, 0.67),

-- RET mutations and fusions
(563, 634, 'missense', 35, 'C634R', 'Pathogenic', 876, 0.34),
(563, 918, 'missense', 35, 'M918T', 'Pathogenic', 654, 0.25),
(563, 1, 'fusion', 1, 'KIF5B-RET', 'Pathogenic', 432, 0.008),
(563, 1, 'fusion', 35, 'RET/PTC', 'Pathogenic', 1234, 0.45),

-- FLT3 mutations (AML)
(127, 835, 'missense', 48, 'D835Y', 'Pathogenic', 1234, 0.28),
(127, 591, 'insertion', 48, 'FLT3-ITD', 'Pathogenic', 2987, 0.67),

-- JAK2 mutations (MPNs)
(339, 617, 'missense', 58, 'V617F', 'Pathogenic', 4321, 0.89),

-- KIT mutations (GIST)
(353, 816, 'missense', 59, 'D816V', 'Pathogenic', 1876, 0.45),
(353, 559, 'deletion', 59, 'W557_K558del', 'Pathogenic', 987, 0.24),

-- VHL mutations (kidney cancer)
(680, 167, 'nonsense', 38, 'R167*', 'Pathogenic', 543, 0.22),
(680, 213, 'missense', 38, 'P213L', 'Pathogenic', 432, 0.18),

-- MYC translocations (lymphomas)
(448, 1, 'translocation', 55, 't(8;14)(q24;q32)', 'Pathogenic', 3456, 0.67),
(448, 1, 'translocation', 53, 't(8;14)', 'Pathogenic', 2341, 0.43),
(448, 1, 'amplification', 24, 'MYC amplification', 'Pathogenic', 1876, 0.15),

-- Additional high-impact mutations
(387, 1010, 'missense', 1, 'D1010Y', 'Pathogenic', 321, 0.02),
(387, 1, 'amplification', 43, 'MET amplification', 'Pathogenic', 765, 0.12),
(86, 1, 'amplification', 24, 'HER2 amplification', 'Pathogenic', 4321, 0.23),
(86, 1, 'amplification', 43, 'HER2 amplification', 'Pathogenic', 876, 0.15),
(308, 61, 'missense', 40, 'Q61R', 'Pathogenic', 234, 0.05),
(308, 12, 'missense', 40, 'G12V', 'Pathogenic', 187, 0.04),

-- NOTCH1 mutations (T-ALL)
(474, 1574, 'frameshift', 49, 'P1574fs', 'Pathogenic', 876, 0.67),
(474, 2514, 'nonsense', 49, 'Q2514*', 'Pathogenic', 543, 0.41),

-- APC mutations (colorectal cancer)
(98, 1450, 'nonsense', 3, 'S1450*', 'Pathogenic', 2987, 0.78),
(98, 1309, 'nonsense', 3, 'T1309*', 'Pathogenic', 1876, 0.52),

-- PTEN mutations (multiple cancers)
(542, 130, 'nonsense', 33, 'R130*', 'Pathogenic', 765, 0.11),
(542, 233, 'missense', 33, 'R233*', 'Pathogenic', 543, 0.08),
(542, 130, 'nonsense', 24, 'R130*', 'Pathogenic', 432, 0.06);

-- ==========================================
-- COMPREHENSIVE THERAPEUTICS (2024 FDA and Clinical Pipeline)
-- ==========================================
INSERT INTO therapeutics (gene_id, drug_name, mechanism_of_action, clinical_status, indication, fda_approval_date, manufacturer, target_mutations) VALUES

-- EGFR Targeted Therapies
(85, 'Erlotinib', 'EGFR tyrosine kinase inhibitor', 'Approved', 'NSCLC with EGFR mutations', '2013-07-12', 'Genentech', 'L858R, exon 19 deletions'),
(85, 'Gefitinib', 'EGFR tyrosine kinase inhibitor', 'Approved', 'NSCLC with EGFR mutations', '2015-07-13', 'AstraZeneca', 'L858R, exon 19 deletions'),
(85, 'Afatinib', 'Pan-ErbB family inhibitor', 'Approved', 'NSCLC with EGFR mutations', '2013-07-12', 'Boehringer Ingelheim', 'L858R, exon 19 deletions, exon 20 insertions'),
(85, 'Osimertinib', 'Third-generation EGFR TKI', 'Approved', 'NSCLC with EGFR T790M', '2017-03-28', 'AstraZeneca', 'T790M, L858R, exon 19 deletions'),
(85, 'Dacomitinib', 'Pan-ErbB family inhibitor', 'Approved', 'NSCLC with EGFR mutations', '2018-09-27', 'Pfizer', 'L858R, exon 19 deletions'),
(85, 'Amivantamab', 'EGFR-MET bispecific antibody', 'Approved', 'NSCLC with EGFR exon 20 insertions', '2024-02-15', 'Janssen', 'exon 20 insertions'),

-- KRAS Targeted Therapies
(360, 'Sotorasib', 'KRAS G12C inhibitor', 'Approved', 'NSCLC with KRAS G12C', '2021-05-28', 'Amgen', 'G12C'),
(360, 'Adagrasib', 'KRAS G12C inhibitor', 'Approved', 'NSCLC and CRC with KRAS G12C', '2024-06-21', 'Mirati Therapeutics', 'G12C'),

-- BRAF Targeted Therapies
(59, 'Vemurafenib', 'BRAF V600E inhibitor', 'Approved', 'Melanoma with BRAF V600E', '2011-08-17', 'Genentech', 'V600E'),
(59, 'Dabrafenib', 'BRAF V600E/K inhibitor', 'Approved', 'Melanoma with BRAF V600E/K', '2013-05-29', 'Novartis', 'V600E, V600K'),
(59, 'Encorafenib', 'BRAF inhibitor', 'Approved', 'Melanoma and CRC with BRAF V600E', '2018-06-27', 'Array BioPharma', 'V600E'),

-- ALK Targeted Therapies
(95, 'Crizotinib', 'ALK/ROS1/MET inhibitor', 'Approved', 'ALK+ NSCLC', '2011-08-26', 'Pfizer', 'ALK fusions'),
(95, 'Ceritinib', 'ALK inhibitor', 'Approved', 'ALK+ NSCLC', '2014-04-29', 'Novartis', 'ALK fusions'),
(95, 'Alectinib', 'ALK inhibitor', 'Approved', 'ALK+ NSCLC', '2015-12-11', 'Genentech', 'ALK fusions'),
(95, 'Brigatinib', 'ALK inhibitor', 'Approved', 'ALK+ NSCLC', '2017-04-28', 'Ariad/Takeda', 'ALK fusions'),
(95, 'Lorlatinib', 'Third-generation ALK inhibitor', 'Approved', 'ALK+ NSCLC', '2018-11-02', 'Pfizer', 'ALK fusions, resistance mutations'),

-- RET Targeted Therapies
(563, 'Selpercatinib', 'RET inhibitor', 'Approved', 'RET-altered cancers', '2024-06-12', 'Lilly', 'RET fusions and mutations'),
(563, 'Pralsetinib', 'RET inhibitor', 'Approved', 'RET-altered cancers', '2020-09-04', 'Blueprint Medicines', 'RET fusions and mutations'),

-- MET Targeted Therapies
(387, 'Tepotinib', 'MET inhibitor', 'Approved', 'NSCLC with MET exon 14 skipping', '2024-02-15', 'Merck KGaA', 'MET exon 14 skipping'),
(387, 'Capmatinib', 'MET inhibitor', 'Approved', 'NSCLC with MET exon 14 skipping', '2020-05-06', 'Novartis', 'MET exon 14 skipping'),

-- HER2 Targeted Therapies
(86, 'Trastuzumab', 'HER2 monoclonal antibody', 'Approved', 'HER2+ breast and gastric cancer', '1998-09-25', 'Genentech', 'HER2 amplification'),
(86, 'Pertuzumab', 'HER2 dimerization inhibitor', 'Approved', 'HER2+ breast cancer', '2012-06-08', 'Genentech', 'HER2 amplification'),
(86, 'T-DM1', 'HER2-targeted ADC', 'Approved', 'HER2+ breast cancer', '2013-02-22', 'Genentech', 'HER2 amplification'),
(86, 'Neratinib', 'Pan-HER inhibitor', 'Approved', 'HER2+ breast cancer', '2017-07-17', 'Puma Biotechnology', 'HER2 amplification'),
(86, 'T-DXd', 'HER2-targeted ADC', 'Approved', 'HER2+ breast and gastric cancer', '2019-12-20', 'Daiichi Sankyo/AstraZeneca', 'HER2 amplification'),
(86, 'Tucatinib', 'HER2 tyrosine kinase inhibitor', 'Approved', 'HER2+ breast cancer', '2020-04-17', 'Seattle Genetics', 'HER2 amplification'),
(86, 'Zanidatamab', 'HER2 bispecific antibody', 'Approved', 'HER2+ bile duct cancer', '2024-11-15', 'Zymeworks', 'HER2 amplification'),

-- FLT3 Targeted Therapies (AML)
(127, 'Midostaurin', 'FLT3 inhibitor', 'Approved', 'FLT3-mutated AML', '2017-04-28', 'Novartis', 'FLT3-ITD, FLT3-TKD'),
(127, 'Gilteritinib', 'FLT3 inhibitor', 'Approved', 'Relapsed FLT3-mutated AML', '2018-11-28', 'Astellas', 'FLT3-ITD, FLT3-TKD'),
(127, 'Quizartinib', 'FLT3 inhibitor', 'Approved', 'FLT3-ITD+ AML', '2023-07-20', 'Daiichi Sankyo', 'FLT3-ITD'),

-- JAK2 Targeted Therapies (MPNs)
(339, 'Ruxolitinib', 'JAK1/2 inhibitor', 'Approved', 'Myelofibrosis, PV', '2011-11-16', 'Incyte', 'JAK2 V617F'),
(339, 'Fedratinib', 'JAK2 inhibitor', 'Approved', 'Myelofibrosis', '2019-08-16', 'Bristol Myers Squibb', 'JAK2 V617F'),
(339, 'Pacritinib', 'JAK2 inhibitor', 'Approved', 'Myelofibrosis', '2022-02-28', 'CTI BioPharma', 'JAK2 V617F'),

-- KIT Targeted Therapies (GIST)
(353, 'Imatinib', 'KIT/PDGFRA/BCR-ABL inhibitor', 'Approved', 'GIST, CML', '2001-05-10', 'Novartis', 'KIT mutations'),
(353, 'Sunitinib', 'Multi-kinase inhibitor', 'Approved', 'GIST, RCC', '2006-01-26', 'Pfizer', 'KIT mutations'),
(353, 'Regorafenib', 'Multi-kinase inhibitor', 'Approved', 'GIST', '2013-02-25', 'Bayer', 'KIT mutations'),
(353, 'Ripretinib', 'KIT/PDGFRA inhibitor', 'Approved', 'Advanced GIST', '2020-05-15', 'Deciphera', 'KIT mutations'),
(353, 'Avapritinib', 'KIT/PDGFRA inhibitor', 'Approved', 'GIST with PDGFRA D842V', '2020-01-09', 'Blueprint Medicines', 'PDGFRA D842V'),

-- IDH Inhibitors
(314, 'Ivosidenib', 'IDH1 inhibitor', 'Approved', 'IDH1-mutated AML and cholangiocarcinoma', '2018-07-20', 'Agios/Servier', 'IDH1 R132H'),
(315, 'Enasidenib', 'IDH2 inhibitor', 'Approved', 'IDH2-mutated AML', '2017-08-01', 'Celgene/Bristol Myers Squibb', 'IDH2 R140Q, R172K'),
(314, 'Vorasidenib', 'IDH1/2 inhibitor', 'Approved', 'IDH-mutated glioma', '2024-08-06', 'Servier', 'IDH1/2 mutations'),

-- PI3K/AKT/mTOR Pathway Inhibitors
(527, 'Alpelisib', 'PIK3CA inhibitor', 'Approved', 'PIK3CA-mutated breast cancer', '2019-05-24', 'Novartis', 'PIK3CA mutations'),
(527, 'Inavolisib', 'PIK3CA inhibitor', 'Approved', 'PIK3CA-mutated breast cancer', '2024-10-10', 'Genentech', 'PIK3CA mutations'),
(97, 'Capivasertib', 'AKT inhibitor', 'Phase III', 'AKT-altered tumors', NULL, 'AstraZeneca', 'AKT mutations'),

-- PARP Inhibitors (DNA Repair Deficiency)
(60, 'Olaparib', 'PARP inhibitor', 'Approved', 'BRCA-mutated breast/ovarian cancer', '2014-12-19', 'AstraZeneca', 'BRCA1/2 mutations'),
(61, 'Rucaparib', 'PARP inhibitor', 'Approved', 'BRCA-mutated ovarian cancer', '2016-12-19', 'Clovis Oncology', 'BRCA1/2 mutations'),
(60, 'Niraparib', 'PARP inhibitor', 'Approved', 'Ovarian cancer maintenance', '2017-03-27', 'Janssen/GSK', 'HRD tumors'),
(61, 'Talazoparib', 'PARP inhibitor', 'Approved', 'BRCA-mutated breast cancer', '2018-10-16', 'Pfizer', 'BRCA1/2 mutations'),

-- CDK4/6 Inhibitors
(71, 'Palbociclib', 'CDK4/6 inhibitor', 'Approved', 'HR+ breast cancer', '2015-02-03', 'Pfizer', 'CDK pathway'),
(71, 'Ribociclib', 'CDK4/6 inhibitor', 'Approved', 'HR+ breast cancer', '2017-03-13', 'Novartis', 'CDK pathway'),
(71, 'Abemaciclib', 'CDK4/6 inhibitor', 'Approved', 'HR+ breast cancer', '2017-09-28', 'Lilly', 'CDK pathway'),

-- Immunotherapies
(1, 'Pembrolizumab', 'PD-1 inhibitor', 'Approved', 'Multiple cancers', '2014-09-04', 'Merck', 'High TMB, MSI-H'),
(1, 'Nivolumab', 'PD-1 inhibitor', 'Approved', 'Multiple cancers', '2014-12-22', 'Bristol Myers Squibb', 'PD-L1 positive'),
(1, 'Atezolizumab', 'PD-L1 inhibitor', 'Approved', 'Multiple cancers', '2016-05-18', 'Genentech', 'PD-L1 positive'),
(1, 'Durvalumab', 'PD-L1 inhibitor', 'Approved', 'NSCLC, bladder cancer', '2017-05-01', 'AstraZeneca', 'PD-L1 positive'),

-- CAR-T Cell Therapies (2024 Approvals)
(66, 'Lisocabtagene maraleucel', 'CD19 CAR-T', 'Approved', 'B-cell lymphomas, CLL/SLL', '2024-05-30', 'Bristol Myers Squibb', 'CD19+ B-cells'),
(66, 'Afamitresgene autoleucel', 'NY-ESO-1 CAR-T', 'Approved', 'Synovial sarcoma', '2024-08-02', 'Adaptimmune', 'NY-ESO-1'),
(66, 'Obecabtagene autoleucel', 'CD19 CAR-T', 'Approved', 'R/R B-ALL', '2024-03-15', 'Autolus', 'CD19+ B-ALL'),

-- Novel 2024 Approvals
(1, 'Tarlatamab', 'DLL3-targeting BiTE', 'Approved', 'Extensive-stage SCLC', '2024-05-16', 'Amgen', 'DLL3+ SCLC'),
(95, 'Repotrectinib', 'NTRK/ALK/ROS1 inhibitor', 'Approved', 'NTRK fusion-positive cancers', '2024-06-13', 'Turning Point Therapeutics', 'NTRK fusions'),
(357, 'Revumenib', 'Menin inhibitor', 'Approved', 'KMT2A-rearranged leukemia', '2024-11-15', 'Syndax Pharmaceuticals', 'KMT2A translocations'),

-- Emerging Therapies
(1, 'Nogapendekin alfa inbakicept', 'IL-15 superagonist', 'Approved', 'BCG-unresponsive bladder cancer', '2024-04-22', 'ImmunityBio', 'Immunomodulatory'),
(680, 'Belzutifan', 'HIF-2α inhibitor', 'Approved', 'VHL-associated tumors', '2021-08-13', 'Merck', 'VHL mutations'),

-- Additional Multi-kinase Inhibitors
(1, 'Sorafenib', 'Multi-kinase inhibitor', 'Approved', 'Hepatocellular carcinoma, RCC', '2005-12-20', 'Bayer', 'Multiple pathways'),
(1, 'Lenvatinib', 'Multi-kinase inhibitor', 'Approved', 'Thyroid cancer, HCC, RCC', '2015-02-13', 'Eisai', 'VEGFR, FGFR'),
(1, 'Cabozantinib', 'MET/VEGFR2 inhibitor', 'Approved', 'RCC, HCC, thyroid cancer', '2012-11-29', 'Exelixis', 'MET, VEGFR2');

-- ==========================================
-- THERAPEUTIC-CANCER TYPE ASSOCIATIONS
-- ==========================================
INSERT INTO therapeutic_cancer_types (therapeutic_id, cancer_type_id) VALUES
-- EGFR inhibitors for NSCLC
(1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1),

-- KRAS inhibitors for NSCLC and CRC
(7, 1), (8, 1), (7, 3), (8, 3),

-- BRAF inhibitors for melanoma
(9, 27), (10, 27), (11, 27), (11, 3),

-- ALK inhibitors for NSCLC
(12, 1), (13, 1), (14, 1), (15, 1), (16, 1),

-- RET inhibitors for thyroid and lung cancers
(17, 35), (18, 35), (17, 1), (18, 1),

-- MET inhibitors for NSCLC
(19, 1), (20, 1),

-- HER2 therapies for breast and gastric cancers
(21, 24), (22, 24), (23, 24), (24, 24), (25, 24), (26, 24), (27, 67),
(21, 43), (25, 43),

-- FLT3 inhibitors for AML
(28, 48), (29, 48), (30, 48),

-- JAK2 inhibitors for MPNs
(31, 58), (32, 58), (33, 58),

-- KIT inhibitors for GIST
(34, 59), (35, 59), (36, 59), (37, 59), (38, 59),

-- IDH inhibitors for AML and glioma
(39, 48), (40, 48), (41, 33), (39, 67),

-- PIK3CA inhibitors for breast cancer
(42, 24), (43, 24),

-- PARP inhibitors for breast and ovarian cancers
(45, 24), (46, 31), (47, 31), (48, 24),
(45, 31), (46, 32), (47, 32),

-- CDK4/6 inhibitors for breast cancer
(49, 24), (50, 24), (51, 24),

-- Immunotherapy for multiple cancers
(52, 1), (52, 27), (52, 40), (52, 46),
(53, 1), (53, 27), (53, 38), (53, 30),
(54, 1), (54, 40), (54, 24), (55, 1), (55, 40),

-- CAR-T therapies for hematologic malignancies
(56, 51), (56, 52), (57, 62), (58, 49),

-- Novel 2024 therapies
(59, 2), (60, 1), (61, 48);

-- Reset auto-increment counters
UPDATE sqlite_sequence SET seq = (SELECT MAX(gene_id) FROM genes) WHERE name = 'genes';
UPDATE sqlite_sequence SET seq = (SELECT MAX(cancer_type_id) FROM cancer_types) WHERE name = 'cancer_types';
UPDATE sqlite_sequence SET seq = (SELECT MAX(mutation_id) FROM mutations) WHERE name = 'mutations';
UPDATE sqlite_sequence SET seq = (SELECT MAX(therapeutic_id) FROM therapeutics) WHERE name = 'therapeutics';

-- Final verification queries
SELECT 'Genes loaded: ' || COUNT(*) FROM genes;
SELECT 'Cancer types loaded: ' || COUNT(*) FROM cancer_types;
SELECT 'Mutations loaded: ' || COUNT(*) FROM mutations;
SELECT 'Therapeutics loaded: ' || COUNT(*) FROM therapeutics;