[phases.setup]
aptPkgs = ["git-lfs", "git"]

[phases.build]
cmds = [
    "git lfs install",
    "git lfs pull",
    "ls -la database/",
    "cd backend && npm install && npm run build",
    "cp -r ../database ./dist/database || echo 'Failed to copy database'"
]

[start]
cmd = "cd backend && npm start"